// generator/lib/site.mjs — renders data/changelog.json into a zero-dependency,
// fully static, subdued/monochrome developer terminal site (system monospace,
// authentic CLI/git-log presentation, dark theme, zero emojis, calm palette).
import { writeText } from './util.mjs'
import { escapeHtml as esc, fmtDateHuman } from './util.mjs'

const SITE = {
  name: 'Freebuff Changelog',
  tagline: 'What actually shipped in Freebuff — reconstructed commit by commit from public diffs.',
  url: process.env.SITE_URL || 'https://freebuff-changelog.pages.dev',
  desc: 'Developer changelog for Freebuff (github.com/CodebuffAI/freebuff). Accurate entries generated by analyzing the git diffs behind every public snapshot.'
}

// ---------------------------------------------------------------------------

const CSS = `
*,*::before,*::after{box-sizing:border-box}
:root{
  color-scheme:dark;
  --bg:#0d1117;
  --panel:#161b22;
  --panel-hover:#1c2128;
  --term-border:#30363d;
  --term-border-strong:#484f58;
  
  --txt:#f0f6fc;
  --txt-dim:#9da7b3;
  --txt-subtle:#768390;
  
  --term-green:#3fb950;
  --term-red:#f85149;
  --term-amber:#d29922;
  --term-cyan:#58a6ff;
  
  --code:#0a0d13;
}

html{
  font:13.5px/1.55 ui-monospace,"SF Mono","Cascadia Mono","JetBrains Mono",Menlo,Monaco,Consolas,monospace;
  background:var(--bg);
  color:var(--txt);
  scroll-behavior:smooth;
  -webkit-font-smoothing:antialiased;
}
body{
  margin:0;
  background:var(--bg);
  color:var(--txt);
  min-height:100vh;
}
main{
  max-width:920px;
  margin:0 auto;
  padding:0 20px 80px;
}
a{
  color:var(--txt);
  text-decoration:underline;
  text-decoration-color:var(--term-border-strong);
  text-underline-offset:2px;
}
a:hover{
  text-decoration-color:var(--term-cyan);
  color:var(--term-cyan);
}
code{
  font:inherit;
  background:var(--code);
  color:var(--txt);
  padding:.1em .35em;
  border-radius:3px;
  border:1px solid var(--term-border);
}

header.top{
  border-bottom:1px solid var(--term-border);
  padding:14px 0;
  margin-bottom:24px;
  display:flex;
  align-items:center;
  justify-content:space-between;
  flex-wrap:wrap;
  gap:12px;
  background:var(--bg);
}
.brand{
  display:flex;
  align-items:center;
  gap:10px;
}
.brand a.logo{
  color:var(--txt);
  font-weight:700;
  display:inline-flex;
  align-items:center;
  gap:6px;
  font-size:1rem;
  text-decoration:none;
}
.brand a.logo:hover{
  text-decoration:none;
  color:#ffffff;
}
.term-prompt-sym{
  color:var(--term-cyan);
  user-select:none;
  font-weight:700;
}
.live-status{
  font-size:.72rem;
  color:var(--term-green);
  border:1px solid rgba(63,185,80,0.3);
  padding:1px 7px;
  border-radius:2px;
  letter-spacing:.03em;
}
nav.term-nav{
  display:flex;
  gap:8px;
  font-size:.84rem;
  flex-wrap:wrap;
}
nav.term-nav a{
  color:var(--txt-dim);
  padding:3px 8px;
  border:1px solid var(--term-border);
  border-radius:2px;
  background:var(--panel);
  text-decoration:none;
  transition:all .1s ease;
}
nav.term-nav a:hover{
  color:#ffffff;
  border-color:var(--term-border-strong);
  text-decoration:none;
}
nav.term-nav a.active{
  color:var(--term-cyan);
  border-color:rgba(88,166,255,0.5);
  background:rgba(88,166,255,0.08);
  text-decoration:none;
}
.nav-feed{
  color:var(--txt-dim)!important;
}

.hero{
  margin-bottom:28px;
}
.term-box{
  background:var(--panel);
  border:1px solid var(--term-border);
  border-radius:3px;
  padding:14px 16px;
}
.term-box-hdr{
  display:flex;
  align-items:center;
  justify-content:space-between;
  border-bottom:1px solid var(--term-border);
  padding-bottom:10px;
  margin-bottom:14px;
  font-size:.82rem;
  color:var(--txt-dim);
  flex-wrap:wrap;
  gap:8px;
}
.term-box-title{
  color:var(--txt);
  font-weight:700;
}
.term-box-head{
  font-size:.8rem;
  color:var(--txt-dim);
}
.term-grid{
  display:grid;
  grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
  gap:12px;
  margin-bottom:14px;
}
.term-stat{
  background:var(--code);
  border:1px solid var(--term-border);
  padding:10px 12px;
  border-radius:2px;
}
.ts-lbl{
  display:block;
  font-size:.68rem;
  color:var(--txt-subtle);
  text-transform:uppercase;
  letter-spacing:.05em;
  margin-bottom:4px;
}
.ts-val{
  display:block;
  font-size:1.45rem;
  color:var(--txt);
  font-weight:700;
  font-variant-numeric:tabular-nums;
  line-height:1.2;
}
.ts-sub{
  display:block;
  font-size:.72rem;
  color:var(--txt-subtle);
  margin-top:2px;
}
.term-footer-bar{
  display:flex;
  justify-content:space-between;
  border-top:1px solid var(--term-border);
  padding-top:10px;
  font-size:.76rem;
  color:var(--txt-subtle);
  flex-wrap:wrap;
  gap:8px;
}

.day{
  margin-top:36px;
}
.day-line{
  display:flex;
  align-items:center;
  justify-content:space-between;
  border-bottom:1px solid var(--term-border);
  padding-bottom:6px;
  margin-bottom:14px;
}
.day-line h2{
  margin:0;
  font-size:.92rem;
  font-weight:700;
  color:var(--txt);
}
.day-line time{
  color:var(--txt);
}
.day-count{
  font-size:.76rem;
  color:var(--txt-subtle);
}

.entry{
  background:var(--panel);
  border:1px solid var(--term-border);
  border-left:3px solid var(--term-border);
  border-radius:2px;
  padding:14px 16px;
  margin:10px 0;
  transition:border-color .12s ease;
}
.entry:hover{
  border-color:var(--term-border-strong);
}
.entry.major{
  border-left-color:var(--txt-dim);
}
.entry.notable{
  border-left-color:var(--term-border-strong);
}
.entry-meta-top{
  display:flex;
  align-items:center;
  gap:8px;
  font-size:.78rem;
  color:var(--txt-subtle);
  margin-bottom:6px;
  flex-wrap:wrap;
}
.commit-ref{
  color:var(--txt-subtle);
  font-weight:600;
}
.commit-ref a{
  color:var(--term-cyan);
  text-decoration:none;
}
.commit-ref a:hover{
  color:#ffffff;
  text-decoration:underline;
}
.entry-utc{
  color:var(--txt-subtle);
}
.badges{
  display:inline-flex;
  gap:5px;
  flex-wrap:wrap;
  align-items:center;
}
.badge{
  font-size:.7rem;
  font-weight:600;
  padding:1px 5px;
  border-radius:2px;
  background:transparent;
  border:1px solid var(--term-border);
  color:var(--txt-subtle);
  text-decoration:none;
}
.badge.maj{
  color:var(--term-amber);
  border-color:rgba(210,153,34,0.45);
  font-weight:700;
}
.badge.not{
  color:var(--txt-dim);
  border-color:var(--term-border-strong);
}
.badge.model{
  color:var(--term-cyan);
  border-color:rgba(88,166,255,0.4);
}
.badge.ver{
  color:var(--term-green);
  border-color:rgba(63,185,80,0.4);
  text-decoration:none;
}
.badge.ver:hover{
  border-color:var(--term-green);
  color:#ffffff;
}
.badge.cat{
  color:var(--txt-subtle);
}
.permalink{
  opacity:0;
  margin-left:auto;
  color:var(--txt-subtle);
  font-size:.85em;
  padding:0 4px;
  text-decoration:none;
}
.entry:hover .permalink{
  opacity:1;
}
.permalink:hover{
  color:var(--term-cyan);
}
.entry h3{
  margin:0 0 8px;
  font-size:1.02rem;
  font-weight:700;
  line-height:1.45;
  color:var(--txt);
}
.entry h3 a{
  color:var(--txt);
  text-decoration:none;
}
.entry h3 a:hover{
  color:var(--term-cyan);
  text-decoration:underline;
}

.model-swap{
  background:var(--code);
  border:1px solid var(--term-border);
  border-radius:2px;
  padding:6px 10px;
  margin:8px 0;
  font-size:.82rem;
  display:flex;
  align-items:center;
  gap:8px;
  flex-wrap:wrap;
}
.model-swap-tag{
  color:var(--term-cyan);
  font-size:.7rem;
  font-weight:700;
  letter-spacing:.04em;
}
.modelplus{
  color:var(--term-green);
  font-weight:600;
}
.modelminus{
  color:var(--term-red);
  font-weight:400;
  text-decoration:line-through;
}
.swap-arrow{
  color:var(--txt-subtle);
}

.summary{
  margin:6px 0;
  font-size:.9rem;
  line-height:1.6;
  color:#d1d7e0;
}
.facts{
  margin:8px 0;
  padding-left:14px;
  border-left:2px solid var(--term-border);
  list-style:none;
}
.facts li{
  color:var(--txt-dim);
  font-size:.82rem;
  margin:3px 0;
}
.facts li::before{
  content:"> ";
  color:var(--term-cyan);
  font-weight:700;
}

.files{
  margin:8px 0 0;
  display:flex;
  flex-wrap:wrap;
  gap:4px;
  align-items:center;
}
.fchip{
  display:inline-block;
  background:var(--code);
  border:1px solid var(--term-border);
  border-radius:2px;
  padding:1px 6px;
  font-size:.74rem;
  color:var(--txt-dim);
}
.fchip.add::before{
  content:"+ ";
  color:var(--term-green);
  font-weight:700;
}
.fchip.del::before{
  content:"− ";
  color:var(--term-red);
  font-weight:700;
}
.fchip.mod::before{
  content:"~ ";
  color:var(--txt-subtle);
}

.diff-viewer{
  margin:10px 0 6px;
  border:1px solid var(--term-border);
  border-radius:2px;
  background:var(--code);
  overflow:hidden;
}
.diff-toggle{
  cursor:pointer;
  padding:6px 10px;
  font-size:.78rem;
  font-weight:600;
  color:var(--txt-dim);
  user-select:none;
  display:flex;
  align-items:center;
  justify-content:space-between;
  background:rgba(255,255,255,0.02);
}
.diff-toggle:hover{
  color:var(--txt);
  background:rgba(255,255,255,0.04);
}
.diff-toggle-left{
  display:inline-flex;
  align-items:center;
  gap:6px;
}
.diff-arrow{
  color:var(--txt-subtle);
  font-weight:700;
  transition:transform .1s ease;
  display:inline-block;
}
.diff-viewer[open] .diff-arrow{
  transform:rotate(90deg);
  color:var(--txt);
}
.diff-viewer[open] .diff-toggle{
  border-bottom:1px solid var(--term-border);
}
.diff-badge{
  font-size:.72rem;
  color:var(--txt-subtle);
}
.diff-body{
  max-height:460px;
  overflow:auto;
  font-family:inherit;
  font-size:.75rem;
  line-height:1.42;
  padding:0;
  background:var(--code);
}
.diff-toolbar{
  display:flex;
  align-items:center;
  justify-content:space-between;
  padding:5px 10px;
  border-bottom:1px solid var(--term-border);
  background:rgba(0,0,0,0.3);
  font-size:.72rem;
  color:var(--txt-subtle);
}
.diff-toolbar-title{
  color:var(--term-cyan);
}
.diff-toolbar-actions{
  display:inline-flex;
  align-items:center;
  gap:8px;
}
.diff-copy-btn,.diff-gh-btn{
  background:none;
  border:none;
  color:var(--txt-dim);
  cursor:pointer;
  padding:0;
  font:inherit;
  font-size:.72rem;
  text-decoration:underline dotted;
}
.diff-copy-btn:hover,.diff-gh-btn:hover{
  color:var(--term-cyan);
}
.diff-pre{
  margin:0;
  font-family:inherit;
  font-size:.75rem;
  line-height:1.42;
  padding:4px 0;
}
.diff-line{
  padding:1px 10px;
  white-space:pre-wrap;
  word-break:break-all;
  display:flex;
  font-family:inherit;
  font-size:.75rem;
  line-height:1.42;
}
.diff-marker{
  width:14px;
  flex-shrink:0;
  user-select:none;
  font-weight:700;
  font-size:.75rem;
}
.diff-text{
  flex-grow:1;
  font-family:inherit;
  font-size:.75rem;
}
.diff-add{
  background:rgba(63,185,80,0.08);
  color:var(--txt);
}
.diff-add .diff-marker{
  color:var(--term-green);
}
.diff-del{
  background:rgba(248,81,73,0.08);
  color:var(--txt-dim);
}
.diff-del .diff-marker{
  color:var(--term-red);
}
.diff-hunk{
  background:rgba(88,166,255,0.06);
  color:var(--term-cyan);
  font-weight:600;
}
.diff-hdr{
  color:var(--txt-subtle);
  font-weight:600;
}
.diff-notice{
  padding:10px;
  color:var(--txt-dim);
  font-size:.75rem;
}
.diff-loading{
  padding:10px;
  display:block;
  color:var(--txt-subtle);
  font-size:.75rem;
}

.metarow{
  display:flex;
  align-items:center;
  justify-content:space-between;
  margin-top:10px;
  padding-top:8px;
  border-top:1px solid var(--term-border);
  font-size:.76rem;
  color:var(--txt-subtle);
  flex-wrap:wrap;
  gap:8px;
}
.diffstat b{
  color:var(--term-green);
  font-weight:700;
}
.diffstat i{
  color:var(--term-red);
  font-style:normal;
}
.meta-links{
  display:inline-flex;
  align-items:center;
  gap:8px;
}
.meta-link{
  color:var(--txt-subtle);
  text-decoration:underline dotted;
}
.meta-link:hover{
  color:var(--term-cyan);
}

.search-input-row{
  display:flex;
  align-items:center;
  gap:8px;
  margin:10px 0;
  background:var(--code);
  border:1px solid var(--term-border);
  padding:6px 10px;
  border-radius:2px;
}
.search-prompt{
  color:var(--term-green);
  font-weight:700;
  white-space:nowrap;
}
#q{
  flex-grow:1;
  background:none;
  border:none;
  color:var(--txt);
  font:inherit;
  outline:none;
}
.search-hint{
  font-size:.72rem;
  color:var(--txt-subtle);
  white-space:nowrap;
}
.filter-chips{
  display:flex;
  align-items:center;
  gap:6px;
  flex-wrap:wrap;
  margin-top:8px;
  font-size:.78rem;
}
.filter-lbl{
  color:var(--txt-subtle);
  font-size:.72rem;
}
.filter-chip{
  background:var(--panel);
  border:1px solid var(--term-border);
  color:var(--txt-dim);
  padding:2px 8px;
  border-radius:2px;
  font:inherit;
  cursor:pointer;
}
.filter-chip:hover{
  border-color:var(--term-border-strong);
  color:#ffffff;
}
.filter-chip.active{
  background:rgba(88,166,255,0.12);
  border-color:var(--term-cyan);
  color:var(--term-cyan);
  font-weight:700;
}
.search-status{
  font-size:.76rem;
  color:var(--txt-subtle);
  margin-top:8px;
}

.grid{
  display:grid;
  grid-template-columns:repeat(auto-fill,minmax(180px,1fr));
  gap:8px;
  margin:12px 0;
}
.tile{
  background:var(--code);
  border:1px solid var(--term-border);
  border-radius:2px;
  padding:8px 10px;
  color:inherit;
  display:block;
}
.tile:hover{
  border-color:var(--term-border-strong);
  text-decoration:none;
}
.tile b{
  display:block;
  font-size:.85rem;
  color:var(--txt);
}
.tile span{
  font-size:.72rem;
  color:var(--txt-dim);
}

.section-hdr{
  border-bottom:1px solid var(--term-border);
  padding-bottom:6px;
  margin:28px 0 12px;
}
.section-hdr h2{
  font-size:.92rem;
  color:var(--txt);
  margin:0;
}
.release-grid{
  display:grid;
  grid-template-columns:repeat(auto-fill,minmax(170px,1fr));
  gap:6px;
  margin-bottom:20px;
}
.release-card{
  background:var(--panel);
  border:1px solid var(--term-border);
  padding:6px 10px;
  border-radius:2px;
  display:flex;
  justify-content:space-between;
  align-items:center;
  font-size:.82rem;
}
.release-card a{
  font-weight:700;
  color:var(--txt);
  text-decoration:none;
}
.release-card a:hover{
  color:#ffffff;
  text-decoration:underline;
}

.archive-year{
  margin-top:20px;
  font-size:1rem;
  color:var(--txt);
  border-bottom:1px solid var(--term-border);
  padding-bottom:4px;
}
.archive-month{
  margin:10px 0 6px;
  font-size:.8rem;
  color:var(--txt-dim);
}
.archive-days{
  display:grid;
  grid-template-columns:repeat(auto-fill,minmax(105px,1fr));
  gap:4px;
  list-style:none;
  padding:0;
  margin:0 0 12px;
}
.archive-days li a{
  display:flex;
  justify-content:space-between;
  padding:3px 6px;
  border-radius:2px;
  background:var(--panel);
  border:1px solid var(--term-border);
  font-size:.76rem;
  color:var(--txt-dim);
  text-decoration:none;
}
.archive-days li a:hover{
  border-color:var(--term-border-strong);
  color:#ffffff;
}

.pr-list{
  display:flex;
  flex-direction:column;
  gap:8px;
  margin-top:12px;
}
.pr-card{
  background:var(--panel);
  border:1px solid var(--term-border);
  border-radius:2px;
  padding:10px 14px;
}
.pr-card-header{
  display:flex;
  justify-content:space-between;
  font-size:.76rem;
  margin-bottom:4px;
}
.pr-status{
  font-weight:700;
}
.pr-status.open{
  color:var(--txt-dim);
}
.pr-status.draft{
  color:var(--txt-subtle);
}
.pr-title{
  margin:0 0 4px;
  font-size:.92rem;
  font-weight:700;
}
.pr-title a{
  color:var(--txt);
}
.pr-meta{
  font-size:.76rem;
  color:var(--txt-subtle);
  display:flex;
  gap:8px;
  flex-wrap:wrap;
}

.man-body{
  padding:6px 0;
  font-size:.84rem;
  line-height:1.6;
}
.man-body h4{
  margin:12px 0 4px;
  color:var(--term-amber);
  font-size:.84rem;
  letter-spacing:.05em;
}
.man-body p{
  margin:0 0 10px;
  color:var(--txt-dim);
}

.pager{
  display:flex;
  justify-content:space-between;
  align-items:center;
  gap:12px;
  margin:24px 0 12px;
  padding-top:12px;
  border-top:1px solid var(--term-border);
}
.pager a{
  color:var(--txt-dim);
  padding:4px 10px;
  border:1px solid var(--term-border);
  border-radius:2px;
  background:var(--panel);
  font-size:.8rem;
  text-decoration:none;
}
.pager a:hover{
  border-color:var(--term-border-strong);
  color:#ffffff;
  text-decoration:none;
}

footer{
  margin-top:48px;
  padding-top:16px;
  border-top:1px solid var(--term-border);
  font-size:.76rem;
  color:var(--txt-subtle);
  display:flex;
  justify-content:space-between;
  align-items:center;
  flex-wrap:wrap;
  gap:8px;
}
.footer-links{
  display:inline-flex;
  gap:12px;
}
.footer-links a{
  color:var(--txt-subtle);
  text-decoration:none;
}
.footer-links a:hover{
  color:var(--txt-dim);
}
`

function miniMd (text) {
  let s = esc(text)
  s = s.replace(/`([^`]+)`/g, '<code>$1</code>')
  s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2" rel="noopener">$1</a>')
  return s
}

function layout ({ title, path, body, desc, noindex }) {
  const abs = (p) => p.startsWith('http') ? p : SITE.url + p
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} · ${SITE.name}</title>
<meta name="description" content="${esc(desc || SITE.desc)}">
${noindex ? '<meta name="robots" content="noindex">' : ''}
<link rel="canonical" href="${abs(path)}">
<meta property="og:title" content="${esc(title)} · ${SITE.name}">
<meta property="og:description" content="${esc(desc || SITE.desc)}">
<meta property="og:type" content="website"><meta property="og:url" content="${abs(path)}">
<link rel="alternate" type="application/rss+xml" title="${SITE.name} (major + notable)" href="${SITE.url}/feed.xml">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='4' fill='%230d1117'/%3E%3Ctext x='5' y='22' font-family='monospace' font-weight='bold' font-size='20' fill='%2358a6ff'%3E%26gt%3B_%3C/text%3E%3C/svg%3E">
<style>${CSS}</style></head><body><main>
<header class="top">
  <div class="brand">
    <a class="logo" href="/">
      <span class="term-prompt-sym">&gt;</span>
      <span>${SITE.name}</span>
    </a>
  </div>
  <nav class="term-nav">
    <a href="/about/" class="${path === '/about/' ? 'active' : ''}">/about</a>
    <a href="/archive/" class="${path.startsWith('/archive/') ? 'active' : ''}">/archive</a>
    <a href="/search/" class="${path.startsWith('/search/') ? 'active' : ''}">/search</a>
    <a href="/in-flight/" class="${path.startsWith('/in-flight/') ? 'active' : ''}">/in-flight</a>
    <a href="/feed.xml" class="nav-feed">/rss</a>
  </nav>
</header>
${body}
<footer>
  <div>freebuff-changes :: unofficial public snapshot mirror reconstructed from <a href="https://github.com/CodebuffAI/freebuff" target="_blank" rel="noopener">CodebuffAI/freebuff</a></div>
  <div class="footer-links">
    <a href="/about/">[about]</a>
    <a href="https://github.com/CodebuffAI/freebuff" target="_blank" rel="noopener">[github]</a>
  </div>
</footer>
<script>
document.addEventListener('keydown', (e) => {
  if (e.key === '/' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) {
    e.preventDefault();
    const q = document.getElementById('q');
    if (q) { q.focus(); q.select(); }
    else { window.location.href = '/search/'; }
  }
});

function copyDiff(btn) {
  const body = btn.closest('.diff-body');
  const pre = body ? body.querySelector('.diff-pre') : null;
  if (!pre) return;
  const text = pre.innerText;
  navigator.clipboard.writeText(text).then(() => {
    const orig = btn.innerText;
    btn.innerText = '[copied!]';
    setTimeout(() => { btn.innerText = orig; }, 1800);
  });
}

document.addEventListener('toggle', async (ev) => {
  const el = ev.target;
  if (!el.classList.contains('diff-viewer') || !el.open || el.dataset.loaded) return;
  const sha = el.dataset.sha;
  const body = el.querySelector('.diff-body');
  if (!sha || !body) return;
  if (body.querySelector('.diff-pre')) { el.dataset.loaded = '1'; return; }
  body.innerHTML = '<span class="diff-loading">Loading diff…</span>';
  try {
    let url = '/diffs/' + sha + '.diff';
    if (location.protocol === 'file:') {
      const idx = location.pathname.lastIndexOf('/dist/');
      if (idx !== -1) {
        url = location.pathname.substring(0, idx + 6) + 'diffs/' + sha + '.diff';
      }
    }
    const res = await fetch(url);
    if (!res.ok) throw new Error('HTTP ' + res.status);
    const text = await res.text();
    el.dataset.loaded = '1';
    renderDiff(body, text, sha);
  } catch (err) {
    const ghUrl = el.dataset.gh || ('https://github.com/CodebuffAI/freebuff/commit/' + sha);
    body.innerHTML = '<div class="diff-notice">Full diff not cached locally. <a href="' + ghUrl + '" target="_blank" rel="noopener">View on GitHub &rarr;</a></div>';
  }
}, true);

function renderDiff(container, text, sha) {
  const lines = text.split(/\\r?\\n/);
  const frag = document.createDocumentFragment();
  
  const toolbar = document.createElement('div');
  toolbar.className = 'diff-toolbar';
  const shortSha = sha.slice(0, 12);
  toolbar.innerHTML = '<span class="diff-toolbar-title">$ git diff ' + shortSha + '^!</span>';
  
  const actions = document.createElement('div');
  actions.className = 'diff-toolbar-actions';
  
  const copyBtn = document.createElement('button');
  copyBtn.className = 'diff-copy-btn';
  copyBtn.textContent = '[copy diff]';
  copyBtn.onclick = () => copyDiff(copyBtn);
  actions.appendChild(copyBtn);
  
  const ghLink = document.createElement('a');
  ghLink.className = 'diff-gh-btn';
  ghLink.href = 'https://github.com/CodebuffAI/freebuff/commit/' + sha;
  ghLink.target = '_blank';
  ghLink.rel = 'noopener';
  ghLink.textContent = '[github]';
  actions.appendChild(ghLink);
  
  toolbar.appendChild(actions);
  frag.appendChild(toolbar);

  const pre = document.createElement('pre');
  pre.className = 'diff-pre';
  for (const line of lines) {
    const row = document.createElement('div');
    row.className = 'diff-line';
    const marker = document.createElement('span');
    marker.className = 'diff-marker';
    const textSpan = document.createElement('span');
    textSpan.className = 'diff-text';
    
    if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('diff --git') || line.startsWith('index ')) {
      row.classList.add('diff-hdr');
      marker.textContent = ' ';
      textSpan.textContent = line;
    } else if (line.startsWith('+')) {
      row.classList.add('diff-add');
      marker.textContent = '+';
      textSpan.textContent = line.slice(1);
    } else if (line.startsWith('-')) {
      row.classList.add('diff-del');
      marker.textContent = '−';
      textSpan.textContent = line.slice(1);
    } else if (line.startsWith('@@')) {
      row.classList.add('diff-hunk');
      marker.textContent = ' ';
      textSpan.textContent = line;
    } else {
      marker.textContent = ' ';
      textSpan.textContent = line.startsWith(' ') ? line.slice(1) : line;
    }
    row.appendChild(marker);
    row.appendChild(textSpan);
    pre.appendChild(row);
  }
  frag.appendChild(pre);

  container.innerHTML = '';
  container.appendChild(frag);
}
</script>
</body></html>`
}

function badges (e) {
  const b = []
  if (e.significance === 'major') b.push('<span class="badge maj">[MAJOR]</span>')
  else if (e.significance === 'notable') b.push('<span class="badge not">[NOTABLE]</span>')
  if (e.modelChanges) b.push('<span class="badge model">[MODEL]</span>')
  if (e.version) b.push(`<a class="badge ver" href="/release/${e.version}/">[v${e.version}]</a>`)
  if (e.kind === 'community' && e.pr) b.push(`<span class="badge">[PR #${e.pr}]</span>`)
  b.push(`<span class="badge cat">[${esc(e.category)}]</span>`)
  return b.join('')
}

function modelDiffLine (e) {
  if (!e.modelChanges) return ''
  const { added = [], removed = [] } = e.modelChanges
  const addHtml = added.map(m => `<span class="modelplus">+${esc(m)}</span>`).join(' ')
  const remHtml = removed.map(m => `<span class="modelminus">−${esc(m)}</span>`).join(' ')
  let swapContent = ''
  if (added.length && removed.length) {
    swapContent = `${addHtml} <span class="swap-arrow">-></span> ${remHtml}`
  } else {
    swapContent = [addHtml, remHtml].filter(Boolean).join(' ')
  }
  return `<div class="model-swap"><span class="model-swap-tag">MODEL SWAP:</span> <span class="model-swap-pills">${swapContent}</span></div>`
}

function shortPath (p) {
  if (p.length <= 36) return p
  const parts = p.split('/')
  if (parts.length > 2) return parts[0] + '/…/' + parts.at(-1)
  return p.slice(0, 16) + '…' + p.slice(-14)
}

function fileChips (e) {
  const chips = []
  for (const p of e.files.added.slice(0, 3)) chips.push(`<span class="fchip add" title="${esc(p)}">${esc(shortPath(p))}</span>`)
  for (const p of e.files.removed.slice(0, 3)) chips.push(`<span class="fchip del" title="${esc(p)}">${esc(shortPath(p))}</span>`)
  for (const p of e.files.modified.slice(0, e.files.added.length + e.files.removed.length ? 3 : 5)) chips.push(`<span class="fchip mod" title="${esc(p)}">${esc(shortPath(p))}</span>`)
  const extra = Math.max(0, e.files.meaningful - chips.length)
  if (extra > 0) chips.push(`<span class="fchip more">+${extra} more</span>`)
  return chips.length ? `<div class="files">${chips.join('')}</div>` : ''
}

function formatDiffHtml (diffText) {
  const lines = diffText.split(/\r?\n/)
  const out = []
  for (const line of lines) {
    if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('diff --git') || line.startsWith('index ')) {
      out.push(`<div class="diff-line diff-hdr"><span class="diff-marker"> </span><span class="diff-text">${esc(line)}</span></div>`)
    } else if (line.startsWith('+')) {
      out.push(`<div class="diff-line diff-add"><span class="diff-marker">+</span><span class="diff-text">${esc(line.slice(1))}</span></div>`)
    } else if (line.startsWith('-')) {
      out.push(`<div class="diff-line diff-del"><span class="diff-marker">−</span><span class="diff-text">${esc(line.slice(1))}</span></div>`)
    } else if (line.startsWith('@@')) {
      out.push(`<div class="diff-line diff-hunk"><span class="diff-marker"> </span><span class="diff-text">${esc(line)}</span></div>`)
    } else {
      out.push(`<div class="diff-line"><span class="diff-marker"> </span><span class="diff-text">${esc(line.startsWith(' ') ? line.slice(1) : line)}</span></div>`)
    }
  }
  return out.join('')
}

function entryCard (e, diffs) {
  const t = fmtDateHuman(e.date)
  const time = e.date.slice(11, 16)
  const anchor = e.sha.slice(0, 12)
  const title = e.ai?.title ? esc(e.ai.title) : esc(e.title || deriveTitleSafe(e))
  const preDiff = diffs?.get ? diffs.get(e.sha) : (diffs ? diffs[e.sha] : null)
  let diffViewer = ''
  if (preDiff) {
    diffViewer = `<details class="diff-viewer" data-sha="${e.sha}">
<summary class="diff-toggle">
  <span class="diff-toggle-left">
    <span class="diff-arrow">&gt;</span>
    <span>View inline diff</span>
  </span>
  <span class="diff-badge">+${e.stats.additions} / −${e.stats.deletions}</span>
</summary>
<div class="diff-body">
  <div class="diff-toolbar">
    <span class="diff-toolbar-title">$ git diff ${anchor}^!</span>
    <div class="diff-toolbar-actions">
      <button class="diff-copy-btn" onclick="copyDiff(this)">[copy diff]</button>
      ${e.compareUrl ? `<a class="diff-gh-btn" href="${esc(e.compareUrl)}" target="_blank" rel="noopener">[github]</a>` : ''}
    </div>
  </div>
  <pre class="diff-pre">${formatDiffHtml(preDiff)}</pre>
</div>
</details>`
  } else if (e.kind === 'sync') {
    diffViewer = `<details class="diff-viewer" data-sha="${e.sha}" data-gh="${esc(e.compareUrl || e.url || '')}">
<summary class="diff-toggle">
  <span class="diff-toggle-left">
    <span class="diff-arrow">&gt;</span>
    <span>View inline diff</span>
  </span>
  <span class="diff-badge">+${e.stats.additions} / −${e.stats.deletions}</span>
</summary>
<div class="diff-body"><span class="diff-loading">Loading diff…</span></div>
</details>`
  }
  return `<article class="entry ${e.significance}" id="${anchor}">
<div class="entry-meta-top">
  <span class="commit-ref">commit <a href="https://github.com/CodebuffAI/freebuff/commit/${e.sha}" target="_blank" rel="noopener">${anchor}</a></span>
  <span class="entry-utc">${esc(time)} UTC</span>
  <div class="badges">${badges(e)}</div>
  <a class="permalink" href="/day/${e.day}/#${anchor}" title="Permalink" aria-label="Permalink">#</a>
</div>
<h3><a href="/day/${e.day}/#${anchor}">${title}</a></h3>
${modelDiffLine(e)}
<div class="summary">${miniMd(e.ai?.summary || e.summary)}</div>
${e.facts?.length ? `<ul class="facts">${e.facts.slice(0, 3).map(f => `<li>${miniMd(f)}</li>`).join('')}</ul>` : ''}
${fileChips(e)}
${diffViewer}
<div class="metarow">
  <span class="diffstat"><b>+${e.stats.additions}</b> / <i>−${e.stats.deletions}</i> &middot; ${e.files.total} file${e.files.total === 1 ? '' : 's'}</span>
  <div class="meta-links">
    ${e.sourceSha ? `<a class="meta-link" href="https://github.com/CodebuffAI/freebuff/commit/${e.sha}" rel="noopener" target="_blank">snapshot</a>` : ''}
    ${e.pr ? `<a class="meta-link" href="${esc(e.prUrl || '')}" rel="noopener" target="_blank">PR #${e.pr}</a>` : ''}
    ${e.compareUrl ? `<a class="meta-link" href="${esc(e.compareUrl)}" rel="noopener" target="_blank">compare</a>` : e.url ? `<a class="meta-link" href="${esc(e.url)}" rel="noopener" target="_blank">commit</a>` : ''}
  </div>
</div></article>`
}

function deriveTitleSafe (e) {
  return (e.summary || '').split(/[.:]/)[0].slice(0, 70) || `${e.category} update`
}

function groupByDay (entries) {
  const out = []
  let cur = null
  for (const e of entries) {
    if (!cur || cur.day !== e.day) { cur = { day: e.day, entries: [] }; out.push(cur) }
    cur.entries.push(e)
  }
  return out
}

// ---------------------------------------------------------------------------

async function write (dist, p, html) { await writeText(`${dist.replace(/\/$/, '')}/${p}`, html) }

export async function buildSite ({ changelog, openPrs, dist, diffs = new Map() }) {
  const entries = [...changelog.entries].reverse() // newest first
  const byDay = groupByDay(entries)
  const major = entries.filter(e => e.significance === 'major')
  const modelEntries = entries.filter(e => e.modelChanges)
  const releases = entries.filter(e => e.version)
  const first = entries.at(-1), last = entries[0]
  const generated = changelog.generatedAt
  const scannedCount = changelog.counts?.commitsScanned || entries.length

  // ----- index: newest days worth of entries
  const NEW_WINDOW = 90
  const idx = []
  let n = 0
  for (const d of byDay) { if (n >= NEW_WINDOW) break; idx.push(d); n += d.entries.length }
  const hero = `
<section class="hero">
  <div class="term-box">
    <div class="term-grid">
      <div class="term-stat">
        <span class="ts-lbl">TRACKED CHANGES</span>
        <b class="ts-val">${entries.length.toLocaleString()}</b>
        <span class="ts-sub">${byDay.length} active dates</span>
      </div>
      <div class="term-stat">
        <span class="ts-lbl">RELEASES</span>
        <b class="ts-val">${releases.length.toLocaleString()}</b>
        <span class="ts-sub">CLI & core pkgs</span>
      </div>
      <div class="term-stat">
        <span class="ts-lbl">COMMITS SCANNED</span>
        <b class="ts-val">${scannedCount.toLocaleString()}</b>
        <span class="ts-sub">from upstream</span>
      </div>
    </div>
    <div class="term-footer-bar">
      <span>HEAD: <a href="https://github.com/CodebuffAI/freebuff/commit/${esc(changelog.headSha || '')}" target="_blank" rel="noopener">${esc((changelog.headSha || '').slice(0, 10))}</a> &middot; updated ${esc(fmtDateHuman(generated))} UTC</span>
      <span>COVERAGE: ${esc(first.day)} &rarr; ${esc(last.day)}</span>
    </div>
  </div>
</section>`

  const daysHtml = idx.map(d =>
    `<section class="day" id="${d.day}">
<div class="day-line">
  <h2><time datetime="${d.day}">== [ ${esc(fmtDateHuman(d.day))} ] ==</time></h2>
  <span class="day-count">${d.entries.length} change${d.entries.length === 1 ? '' : 's'}</span>
</div>
${d.entries.map(e => entryCard(e, diffs)).join('\n')}</section>`).join('')

  await write(dist, 'index.html', layout({ title: 'Home', path: '/', body: hero + daysHtml +
    `<div class="pager"><a href="/archive/">[ full archive &rarr; ]</a><a href="/feed.xml">[ rss feed ]</a></div>` }))

  // ----- per-day pages
  for (let i = 0; i < byDay.length; i++) {
    const d = byDay[i]
    const prevDay = i < byDay.length - 1 ? byDay[i + 1] : null
    const nextDay = i > 0 ? byDay[i - 1] : null
    const dayPager = `<div class="pager">` +
      (prevDay ? `<a href="/day/${prevDay.day}/">&larr; ${esc(fmtDateHuman(prevDay.day))}</a>` : '<span></span>') +
      (nextDay ? `<a href="/day/${nextDay.day}/">${esc(fmtDateHuman(nextDay.day))} &rarr;</a>` : '<span></span>') +
      `</div>`
    await write(dist, `day/${d.day}/index.html`, layout({
      title: fmtDateHuman(d.day), path: `/day/${d.day}/`,
      desc: `${d.entries.length} Freebuff changes on ${d.day}`,
      body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">DAILY_LOG :: ${esc(d.day)}</span><span>${d.entries.length} entries</span></div><p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">Reconstructed public snapshot commits pushed to CodebuffAI/freebuff on this date.</p></div></section>` +
        dayPager +
        `<section class="day">${d.entries.map(e => entryCard(e, diffs)).join('\n')}</section>` +
        dayPager +
        `<p style="margin-top:20px;font-size:.82rem"><a href="/">&larr; [latest]</a> &middot; <a href="/archive/">[archive]</a></p>`
    }))
  }

  // ----- release pages
  const verMap = new Map()
  for (const e of releases) verMap.set(e.version, e)
  const vers = [...verMap.values()]
  vers.sort((a, b) => a.date < b.date ? -1 : 1)
  for (let i = 0; i < vers.length; i++) {
    const rel = vers[i]
    const lo = i > 0 ? vers[i - 1].date : '0000'
    const mine = entries.filter(e => e.date > lo && e.date <= rel.date && e.sha !== rel.sha)
    const prevRel = i > 0 ? vers[i - 1] : null
    const nextRel = i < vers.length - 1 ? vers[i + 1] : null
    const relPager = `<div class="pager">` +
      (prevRel ? `<a href="/release/${prevRel.version}/">&larr; v${esc(prevRel.version)}</a>` : '<span></span>') +
      (nextRel ? `<a href="/release/${nextRel.version}/">v${esc(nextRel.version)} &rarr;</a>` : '<span></span>') +
      `</div>`
    await write(dist, `release/${rel.version}/index.html`, layout({
      title: `Release ${rel.version}`, path: `/release/${rel.version}/`,
      desc: `Freebuff v${rel.version} — ${mine.length} changes since the previous release.`,
      body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">RELEASE_TAG :: v${esc(rel.version)}</span><span>${esc(rel.date.slice(0, 10))}</span></div><p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">Freebuff v${esc(rel.version)} &middot; commit <code>${rel.sha.slice(0, 10)}</code> &middot; ${mine.length} commits since previous release.</p></div></section>` +
        relPager +
        `<section class="day">${[rel, ...mine].map(e => entryCard(e, diffs)).join('\n')}</section>` +
        relPager +
        `<p style="margin-top:20px;font-size:.82rem"><a href="/archive/#releases">&larr; [all releases]</a> &middot; <a href="/">[latest]</a></p>`
    }))
  }

  // ----- archive (all days + releases + categories)
  const cats = new Map()
  for (const e of entries) cats.set(e.category, (cats.get(e.category) || 0) + 1)
  const catTiles = [...cats.entries()].sort((a, b) => b[1] - a[1]).map(([c, k]) =>
    `<a class="tile" href="/search/?q=${encodeURIComponent(c)}"><b>${esc(c)}</b><span>${k.toLocaleString()} changes</span></a>`).join('')
  
  const relCards = [...vers].reverse().map(v =>
    `<div class="release-card"><a href="/release/${v.version}/">v${esc(v.version)}</a><span style="font-size:.74rem;color:var(--txt-subtle)">${esc(v.date.slice(0, 10))}</span></div>`
  ).join('')

  const years = new Map()
  for (const d of byDay) {
    const y = d.day.slice(0, 4)
    const m = d.day.slice(0, 7)
    if (!years.has(y)) years.set(y, new Map())
    const months = years.get(y)
    if (!months.has(m)) months.set(m, [])
    months.get(m).push(d)
  }
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const yearSections = [...years.entries()].map(([y, months]) => {
    const monthHtml = [...months.entries()].map(([m, days]) => {
      const [, mo] = m.split('-')
      const name = monthNames[Number(mo) - 1]
      const dayItems = days.map(d => `<li><a href="/day/${d.day}/"><span>${d.day.slice(8)}</span><span style="font-size:.7rem;color:var(--txt-subtle)">${d.entries.length}</span></a></li>`).join('')
      return `<h4 class="archive-month">${name} ${y}</h4><ul class="archive-days">${dayItems}</ul>`
    }).join('')
    return `<h3 class="archive-year">${y}</h3>${monthHtml}`
  }).join('')

  await write(dist, 'archive/index.html', layout({
    title: 'Archive', path: '/archive/',
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">ARCHIVE_INDEX :: historical directory</span>
      <span>${entries.length.toLocaleString()} total commits</span>
    </div>
    <div style="font-size:.76rem;color:var(--txt-subtle);margin-bottom:6px">CATEGORIES:</div>
    <div class="grid">${catTiles}</div>
  </div>
</section>
<div class="section-hdr">
  <h2 id="releases">== RELEASES (${vers.length}) ==</h2>
</div>
<div class="release-grid">${relCards}</div>
<div class="section-hdr">
  <h2>== DAYS BY MONTH (${byDay.length} DATES) ==</h2>
</div>
${yearSections}`
  }))

  // ----- search (compact index with client URL derivation + ?q= support + filter chips)
  const idxJson = entries.map(e => ({
    d: e.day,
    t: (e.ai?.title || e.title || deriveTitleSafe(e)).slice(0, 90),
    c: e.category,
    s: e.sha.slice(0, 12),
    a: e.significance
  }))
  await write(dist, 'search-index.json', JSON.stringify(idxJson))
  await write(dist, 'search/index.html', layout({
    title: 'Search', path: '/search/',
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">QUERY_ENGINE :: Freebuff Changelog</span>
      <span>${entries.length.toLocaleString()} indexed entries</span>
    </div>
    <div class="search-input-row">
      <span class="search-prompt">$ grep -i</span>
      <input id="q" type="search" placeholder="regex / pattern (e.g. muse, claude, CLI, release)..." autocomplete="off" autofocus>
      <span class="search-hint">[press / to focus]</span>
    </div>
    <div class="filter-chips">
      <span class="filter-lbl">FLAGS:</span>
      <button class="filter-chip active" data-filter="">--all</button>
      <button class="filter-chip" data-filter="model">--models</button>
      <button class="filter-chip" data-filter="major">--major</button>
      <button class="filter-chip" data-filter="release">--releases</button>
      <button class="filter-chip" data-filter="CLI">--cli</button>
      <button class="filter-chip" data-filter="prompt">--prompt</button>
      <button class="filter-chip" data-filter="desktop">--desktop</button>
    </div>
    <div class="search-status"><span id="match-count"></span></div>
  </div>
</section>

<div id="hits"></div>

<script>
fetch('/search-index.json').then(r=>r.json()).then(ix=>{
  let t;
  const q = document.getElementById('q'), h = document.getElementById('hits'), cnt = document.getElementById('match-count');
  const chips = document.querySelectorAll('.filter-chip');
  const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  
  const go = () => {
    const v = q.value.trim().toLowerCase();
    if (!v) { h.innerHTML = ''; cnt.textContent = ''; return; }
    const w = v.split(/\\s+/);
    const hits = ix.filter(e => {
      const s = (e.t + ' ' + e.c + ' ' + (e.a || '')).toLowerCase();
      return w.every(x => s.includes(x));
    }).slice(0, 200);
    
    cnt.textContent = hits.length ? ('MATCHES: ' + hits.length + (hits.length === 200 ? '+ (capped at 200)' : '')) : 'MATCHES: 0';
    h.innerHTML = hits.map(e => {
      const u = '/day/' + e.d + '/#' + e.s;
      const sigTag = e.a === 'major' ? '<span class="badge maj">[MAJOR]</span>' : (e.a === 'notable' ? '<span class="badge not">[NOTABLE]</span>' : '');
      return '<article class="entry ' + (e.a || '') + '"><div class="entry-meta-top">' +
        '<span class="commit-ref">commit ' + esc(e.s) + '</span>' +
        '<span class="entry-utc">' + esc(e.d) + '</span>' +
        '<div class="badges"><span class="badge cat">[' + esc(e.c) + ']</span>' + sigTag + '</div>' +
        '</div>' +
        '<h3><a href="' + u + '">' + esc(e.t) + '</a></h3>' +
        '</article>';
    }).join('') || '<p style="color:var(--txt-subtle);margin:20px 0">$ No matches found for pattern.</p>';
  };

  q.addEventListener('input', () => {
    chips.forEach(c => c.classList.remove('active'));
    clearTimeout(t);
    t = setTimeout(go, 90);
  });

  chips.forEach(chip => {
    chip.addEventListener('click', () => {
      chips.forEach(c => c.classList.remove('active'));
      chip.classList.add('active');
      q.value = chip.dataset.filter || '';
      go();
    });
  });

  const params = new URLSearchParams(window.location.search);
  const initialQ = params.get('q') || (window.location.hash.startsWith('#q=') ? decodeURIComponent(window.location.hash.slice(3)) : '');
  if (initialQ) {
    q.value = initialQ;
    chips.forEach(c => {
      if (c.dataset.filter && initialQ.toLowerCase().includes(c.dataset.filter.toLowerCase())) c.classList.add('active');
      else if (!c.dataset.filter && !initialQ) c.classList.add('active');
      else c.classList.remove('active');
    });
    go();
  }
});
</script>`
  }))

  // ----- about (user-facing overview)
  await write(dist, 'about/index.html', layout({
    title: 'About', path: '/about/',
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">ABOUT :: Freebuff Changelog</span>
      <span>${entries.length.toLocaleString()} tracked changes</span>
    </div>
    <div class="man-body">
      <h4>WHAT IS THIS?</h4>
      <p>Freebuff Changelog is an automated, developer-focused changelog for <a href="https://github.com/CodebuffAI/freebuff" target="_blank" rel="noopener">CodebuffAI/freebuff</a>. It provides chronological visibility into everything that ships—reconstructed commit-by-commit directly from public git diffs.</p>
      
      <h4>WHY IT EXISTS</h4>
      <p>The upstream Freebuff repository is updated via automated snapshot merges that frequently arrive with blank <em>"Sync public snapshot"</em> messages. Without commit notes, it is difficult to see when an AI model was replaced, when a new command was added, or what bug was fixed.</p>
      <p>This project inspects the code diff behind every snapshot (${entries.length.toLocaleString()} tracked changes from ${scannedCount.toLocaleString()} scanned commits) to extract meaningful updates so developers and users always know what is new.</p>
      
      <h4>WHAT WE TRACK</h4>
      <p><strong>Model Lineup:</strong> Additions, retirements, and swaps in the free model catalog.<br>
      <strong>Releases:</strong> CLI version bumps (<code>v1.0.x</code>) and feature highlights.<br>
      <strong>Commands:</strong> New slash commands, CLI flags, and workflow capabilities.<br>
      <strong>Code Diffs:</strong> Clean unified diffs with syntax highlighting so you can inspect the exact code changes.</p>
      
      <h4>VERIFIABLE & OPEN</h4>
      <p>Every entry links directly to the underlying GitHub commit and snapshot compare view for complete ground truth. Stay up to date via the <a href="/feed.xml">RSS feed</a>, explore historical changes in the <a href="/archive/">Archive</a>, or inspect upcoming community contributions on the <a href="/in-flight/">In-Flight PRs</a> page.</p>
    </div>
  </div>
</section>`
  }))

  // ----- open PRs page (community activity ahead of merges)
  if (openPrs?.length) {
    const cards = openPrs.map(p => {
      const stats = (p.additions != null && p.deletions != null)
        ? `<span class="diffstat"><b>+${p.additions}</b> / <i>−${p.deletions}</i></span>`
        : ''
      return `<article class="pr-card">
  <div class="pr-card-header">
    <span class="pr-status ${p.draft ? 'draft' : 'open'}">[${p.draft ? 'DRAFT' : 'OPEN PR'}]</span>
    <a href="${esc(p.url)}" target="_blank" rel="noopener">#${p.number}</a>
  </div>
  <h3 class="pr-title"><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.title)}</a></h3>
  <div class="pr-meta">
    <span>#${p.number} by ${esc(p.author || 'contributor')}</span>
    <span>&middot;</span>
    <span>${esc((p.updated || p.created || '').slice(0, 10))}</span>
    ${stats ? `<span>&middot;</span>${stats}` : ''}
    ${p.draft ? '<span>&middot;</span><span style="color:var(--txt-subtle)">draft</span>' : ''}
  </div>
</article>`
    }).join('')

    await write(dist, 'in-flight/index.html', layout({
      title: 'In flight', path: '/in-flight/',
      body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">PULL_REQUESTS :: CodebuffAI/freebuff [in flight]</span>
      <span>${openPrs.length} open</span>
    </div>
    <p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">
      Community contributions awaiting merge or snapshot sync. Updated ${esc(fmtDateHuman(generated))} UTC.
    </p>
  </div>
</section>
<div class="pr-list">${cards}</div>`
    }))
  }

  // ----- feeds / api
  const feedEntries = entries.filter(e => e.significance !== 'minor').slice(0, 60)
  const items = feedEntries.map(e => {
    const title = e.ai?.title || e.title || deriveTitleSafe(e)
    return `<item><title>${esc(title)}</title><link>${SITE.url}/day/${e.day}/#${e.sha.slice(0, 12)}</link>
<guid isPermaLink="false">${esc(e.sha)}</guid><pubDate>${new Date(e.date).toUTCString()}</pubDate>
<description>${esc(title)} — ${esc((e.ai?.summary || e.summary || '').replace(/[*`#]/g, ''))}</description></item>`
  }).join('')
  await write(dist, 'feed.xml',
    `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${SITE.name} (unofficial)</title>
<link>${SITE.url}</link><atom:link href="${SITE.url}/feed.xml" rel="self" type="application/rss+xml" /><description>${esc(SITE.desc)}</description><language>en</language><lastBuildDate>${new Date(generated).toUTCString()}</lastBuildDate>${items}</channel></rss>`)

  await write(dist, 'changelog.json', JSON.stringify(changelog))
  await write(dist, 'api/entries.json', JSON.stringify({ generatedAt: generated, head: changelog.headSha, total: entries.length, latest: entries.slice(0, 60) }))

  // ----- sitemap / robots / headers / 404
  const urls = ['/']
  for (const d of byDay) urls.push(`/day/${d.day}/`)
  for (const v of vers) urls.push(`/release/${v.version}/`)
  urls.push('/archive/', '/search/', '/about/')
  if (openPrs?.length) urls.push('/in-flight/')
  await write(dist, 'sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u => `<url><loc>${SITE.url}${u}</loc></url>`).join('')}</urlset>`)
  await write(dist, 'robots.txt', `User-agent: *\nAllow: /\nSitemap: ${SITE.url}/sitemap.xml\n`)
  await write(dist, '_headers', `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
/api/*
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=300
/*.json
  Access-Control-Allow-Origin: *
/index.html
  Cache-Control: public, max-age=300
/changelog.json
  Cache-Control: public, max-age=300
/search-index.json
  Cache-Control: public, max-age=3600
/feed.xml
  Cache-Control: public, max-age=600
/sitemap.xml
  Cache-Control: public, max-age=86400
/day/*
  Cache-Control: public, max-age=86400
/release/*
  Cache-Control: public, max-age=86400
/diffs/*
  Content-Type: text/plain; charset=utf-8
  Cache-Control: public, max-age=31536000, immutable
  Access-Control-Allow-Origin: *
`)
  await write(dist, '404.html', layout({ title: 'Not found', path: '/404', noindex: true, body: '<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">ERROR :: 404 NOT FOUND</span></div><p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">No commit or snapshot shipped at this path. <a href="/">&larr; [back to index]</a></p></div></section>' }))
  return { entries: entries.length, days: byDay.length, releases: vers.length }
}
