// generator/lib/site.mjs — renders data/changelog.json into a zero-dependency,
// fully static, extremely fast site (single inline CSS, no client JS except the
// search page, system fonts, everything pre-rendered).
import { writeText } from './util.mjs'
import { escapeHtml as esc, fmtDateHuman } from './util.mjs'

const SITE = {
  name: 'Freebuff Changes',
  tagline: 'What actually shipped in Freebuff — reconstructed from the public repo, commit by commit.',
  url: process.env.SITE_URL || 'https://freebuff-changelog.pages.dev',
  desc: 'Unofficial changelog for Freebuff (github.com/CodebuffAI/freebuff). Accurate entries generated by analyzing the diffs behind every public snapshot.'
}

// ---------------------------------------------------------------------------

const CSS = `
*,*::before,*::after{box-sizing:border-box}
:root{color-scheme:light dark;--bg:#0b0e14;--card:#11151f;--line:#1d2433;--txt:#dfe5f0;--dim:#8a93a8;
--acc:#5ccfe6;--maj:#ffd16c;--no:#95e08b;--min:#5a6478;--code:#151b28;--badge:#161d2c}
@media(prefers-color-scheme:light){:root{--bg:#f7f8fb;--card:#fff;--line:#e3e7ef;--txt:#1a2233;--dim:#5b6678;
--acc:#0a7ea4;--maj:#a16207;--no:#2e7d32;--min:#7b8496;--code:#eef1f7;--badge:#eef1f7}}
html{font:16px/1.6 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
body{margin:0;background:var(--bg);color:var(--txt)}
main{max-width:860px;margin:0 auto;padding:0 20px 80px}
a{color:var(--acc);text-decoration:none}a:hover{text-decoration:underline}
code{font:.85em ui-monospace,"SF Mono",Cascadia Mono,Consolas,monospace;background:var(--code);padding:.1em .35em;border-radius:4px}
header.top{display:flex;gap:14px;align-items:baseline;padding:26px 0 6px;flex-wrap:wrap}
header.top .logo{font-weight:800;font-size:1.25rem;letter-spacing:-.02em;color:var(--txt)}
header.top nav{margin-left:auto;font-size:.9rem;display:flex;gap:16px}
.hero{padding:26px 0 10px}.hero h1{font-size:1.9rem;letter-spacing:-.03em;margin:0 0 8px}
.hero p{color:var(--dim);margin:0;max-width:60ch}
.stats{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 6px}
.stat{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:10px 16px;font-size:.85rem;color:var(--dim)}
.stat b{display:block;font-size:1.35rem;color:var(--txt);font-variant-numeric:tabular-nums}
.day{margin-top:34px}.day h2{font-size:.95rem;color:var(--dim);text-transform:uppercase;letter-spacing:.08em;
border-bottom:1px solid var(--line);padding-bottom:6px}
.day h2 time{color:var(--txt)}
.entry{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--min);border-radius:10px;
padding:14px 16px;margin:12px 0}
.entry.major{border-left-color:var(--maj)}.entry.notable{border-left-color:var(--no)}
.entry h3{margin:0 0 4px;font-size:1.02rem;letter-spacing:-.01em}
.badges{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 8px}
.badge{font-size:.72rem;background:var(--badge);border:1px solid var(--line);color:var(--dim);
border-radius:99px;padding:2px 9px;font-weight:600}
.badge.maj{color:var(--maj);border-color:var(--maj)}.badge.not{color:var(--no);border-color:var(--no)}
.badge.model{color:var(--acc);border-color:var(--acc)}.badge.ver{color:var(--txt)}
.summary{margin:6px 0;font-size:.93rem}
.files{margin:8px 0 0;font-size:.8rem;color:var(--dim)}
.fchip{display:inline-block;background:var(--code);border-radius:5px;padding:1px 7px;margin:2px 4px 2px 0}
.fchip.add::before{content:"+ ";color:var(--no)}.fchip.del::before{content:"− ";color:#f07178}
.fchip.mod::before{content:"~ ";color:var(--dim)}
.modelplus{color:var(--no);font-weight:700}.modelminus{color:#f07178;font-weight:700;text-decoration:line-through}
.facts{margin:6px 0;padding-left:18px;border-left:2px solid var(--line)}
.facts li{color:var(--dim);font-size:.83rem;margin:3px 0}
.metarow{display:flex;gap:12px;align-items:center;margin-top:8px;font-size:.78rem;color:var(--dim)}
.metarow a{color:var(--dim);text-decoration:underline dotted}
.diffstat b{color:var(--no)}.diffstat i{color:#f07178;font-style:normal}
footer{margin-top:60px;padding-top:18px;border-top:1px solid var(--line);font-size:.8rem;color:var(--dim)}
.daysub{font-size:.8rem;font-weight:400;color:var(--dim);margin-left:8px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px;margin:14px 0}
.tile{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 14px}
.tile b{display:block}.tile span{font-size:.8rem;color:var(--dim)}
#q{width:100%;padding:12px 14px;font:inherit;background:var(--card);color:var(--txt);border:1px solid var(--line);border-radius:10px}
#hits{margin-top:6px}
.muted{color:var(--dim);font-size:.85rem}
.pager{display:flex;gap:14px;margin:20px 0}
`

function miniMd (text) {
  let s = esc(text)
  s = s.replace(/`([^`]+)`/g, '<code>$1</code>')
  s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2" rel="noopener">$1</a>')
  return s
}

function layout ({ title, path, body, desc, noindex }) {
  const abs = (p) => p.startsWith('http') ? p : SITE.url + p
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} · ${SITE.name}</title>
<meta name="description" content="${esc(desc || SITE.desc)}">
${noindex ? '<meta name="robots" content="noindex">' : ''}
<link rel="canonical" href="${abs(path)}">
<meta property="og:title" content="${esc(title)} · ${SITE.name}">
<meta property="og:description" content="${esc(desc || SITE.desc)}">
<meta property="og:type" content="website"><meta property="og:url" content="${abs(path)}">
<link rel="alternate" type="application/rss+xml" title="${SITE.name} (major + notable)" href="${SITE.url}/feed.xml">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='0.9em' font-size='90'%3E📜%3C/text%3E%3C/svg%3E">
<style>${CSS}</style></head><body><main>
<header class="top"><a class="logo" href="/">📜 ${SITE.name}</a><nav>
<a href="/about/">About</a><a href="/archive/">Archive</a><a href="/search/">Search</a><a href="/feed.xml">RSS</a>
</nav></header>
${body}
<footer>Unofficial community project — not affiliated with Codebuff. Data source:
<a href="https://github.com/CodebuffAI/freebuff">github.com/CodebuffAI/freebuff</a> public snapshot diffs.
<a href="/about/">How this is generated</a></footer>
</main></body></html>`
}

function badges (e) {
  const b = []
  if (e.significance === 'major') b.push('<span class="badge maj">major</span>')
  else if (e.significance === 'notable') b.push('<span class="badge not">notable</span>')
  if (e.modelChanges) b.push('<span class="badge model">model lineup</span>')
  if (e.version) b.push(`<a class="badge ver" href="/release/${e.version}/">v${e.version}</a>`)
  if (e.kind === 'community' && e.pr) b.push(`<span class="badge">PR #${e.pr}</span>`)
  b.push(`<span class="badge">${esc(e.category)}</span>`)
  if (e.ai?.title) b.push('<span class="badge" title="summary AI-assisted from the exact diff">ai</span>')
  return b.join('')
}

function modelDiffLine (e) {
  if (!e.modelChanges) return ''
  const { added = [], removed = [] } = e.modelChanges
  const parts = []
  if (added.length) parts.push(added.map(m => `<span class="modelplus">+${esc(m)}</span>`).join(' '))
  if (removed.length) parts.push(removed.map(m => `<span class="modelminus">−${esc(m)}</span>`).join(' '))
  return `<div class="summary">${parts.join(' → ')}</div>`
}

function fileChips (e) {
  const chips = []
  for (const p of e.files.added.slice(0, 3)) chips.push(`<span class="fchip add">${esc(p)}</span>`)
  for (const p of e.files.removed.slice(0, 3)) chips.push(`<span class="fchip del">${esc(p)}</span>`)
  for (const p of e.files.modified.slice(0, e.files.added.length + e.files.removed.length ? 3 : 5)) chips.push(`<span class="fchip mod">${esc(p)}</span>`)
  const extra = Math.max(0, e.files.meaningful - chips.length)
  if (extra > 0) chips.push(`<span class="fchip">+${extra} more</span>`)
  return chips.length ? `<div class="files">${chips.join('')}</div>` : ''
}

function entryCard (e) {
  const t = fmtDateHuman(e.date)
  const time = e.date.slice(11, 16)
  const anchor = e.sha.slice(0, 12)
  return `<article class="entry ${e.significance}" id="${anchor}">
<h3>${e.ai?.title ? esc(e.ai.title) : esc(e.title || deriveTitleSafe(e))}</h3>
${modelDiffLine(e)}
<div class="badges">${badges(e)}</div>
<div class="summary">${miniMd(e.ai?.summary || e.summary)}</div>
${e.facts?.length ? `<ul class="facts">${e.facts.slice(0, 3).map(f => `<li>${miniMd(f)}</li>`).join('')}</ul>` : ''}
${fileChips(e)}
<div class="metarow"><span>${esc(t)} ${esc(time)} UTC</span>
<span class="diffstat"><b>+${e.stats.additions}</b> / <i>−${e.stats.deletions}</i> · ${e.files.total} files</span>
${e.sourceSha ? `<a href="https://github.com/CodebuffAI/freebuff/commit/${e.sha}" rel="noopener">snapshot ${anchor}</a>` : ''}
${e.pr ? `<a href="${esc(e.prUrl || '')}" rel="noopener">PR #${e.pr}</a>` : ''}
${e.compareUrl ? `<a href="${esc(e.compareUrl)}" rel="noopener">diff</a>` : e.url ? `<a href="${esc(e.url)}" rel="noopener">commit</a>` : ''}
</div></article>`
}

function deriveTitleSafe (e) {
  return (e.summary || '').split(/[.:]/)[0].slice(0, 70) || `${e.category} update`
}

function groupByDay (entries) {
  const out = []
  let cur = null
  for (const e of entries) {
    if (!cur || cur.day !== e.day) { cur = { day: e.day, entries: [] }; out.push(cur) }
    cur.entries.push(e)
  }
  return out
}

// ---------------------------------------------------------------------------

async function write (dist, p, html) { await writeText(`${dist.replace(/\/$/, '')}/${p}`, html) }

export async function buildSite ({ changelog, openPrs, dist }) {
  const entries = [...changelog.entries].reverse() // newest first
  const byDay = groupByDay(entries)
  const major = entries.filter(e => e.significance === 'major')
  const modelEntries = entries.filter(e => e.modelChanges)
  const releases = entries.filter(e => e.version)
  const first = entries.at(-1), last = entries[0]
  const generated = changelog.generatedAt

  // ----- index: newest days worth of entries
  const NEW_WINDOW = 90
  const idx = []
  let n = 0
  for (const d of byDay) { if (n >= NEW_WINDOW) break; idx.push(d); n += d.entries.length }
  const hero = `
<section class="hero"><h1>${SITE.name}</h1><p>${SITE.tagline}</p>
<div class="stats">
<div class="stat"><b>${entries.length.toLocaleString()}</b> changes tracked</div>
<div class="stat"><b>${releases.length.toLocaleString()}</b> releases</div>
<div class="stat"><b>${modelEntries.length}</b> model-lineup changes</div>
<div class="stat"><b>${changelog.counts?.commitsScanned || entries.length}</b> upstream commits analyzed</div>
</div>
<p class="muted">Covering ${esc(first.day)} → ${esc(last.day)} (UTC). Latest snapshot analyzed: <code>${esc((changelog.headSha || '').slice(0, 12))}</code> · updated ${esc(fmtDateHuman(generated))}.</p>
</section>`
  const daysHtml = idx.map(d =>
    `<section class="day" id="${d.day}"><h2><time>${esc(fmtDateHuman(d.day))}</time><span class="daysub">${d.entries.length} change${d.entries.length === 1 ? '' : 's'}</span></h2>
${d.entries.map(entryCard).join('\n')}</section>`).join('')
  await write(dist, 'index.html', layout({ title: 'Home', path: '/', body: hero + daysHtml +
    `<div class="pager"><a href="/archive/">Full archive →</a><a href="/feed.xml">RSS (major & notable)</a></div>` }))

  // ----- per-day pages
  for (const d of byDay) {
    await write(dist, `day/${d.day}/index.html`, layout({
      title: fmtDateHuman(d.day), path: `/day/${d.day}/`,
      desc: `${d.entries.length} Freebuff changes on ${d.day}`,
      body: `<section class="hero"><h1><time>${esc(fmtDateHuman(d.day))}</time></h1><p>${d.entries.length} change${d.entries.length === 1 ? '' : 's'} pushed to the public repo this day.</p></section>` +
        `<section class="day">${d.entries.map(entryCard).join('\n')}</section>` +
        `<p><a href="/">← Latest</a> · <a href="/archive/">Archive</a></p>`
    }))
  }

  // ----- release pages
  const verMap = new Map()
  for (const e of releases) verMap.set(e.version, e)
  const vers = [...verMap.values()]
  vers.sort((a, b) => a.date < b.date ? -1 : 1)
  for (let i = 0; i < vers.length; i++) {
    const rel = vers[i]
    const lo = i > 0 ? vers[i - 1].date : '0000'
    const mine = entries.filter(e => e.date > lo && e.date <= rel.date && e.sha !== rel.sha)
    await write(dist, `release/${rel.version}/index.html`, layout({
      title: `Release ${rel.version}`, path: `/release/${rel.version}/`,
      desc: `Freebuff v${rel.version} — ${mine.length} changes since the previous release.`,
      body: `<section class="hero"><h1>Freebuff v${esc(rel.version)}</h1><p>Released ${esc(fmtDateHuman(rel.date))} UTC · <code>${rel.sha.slice(0, 12)}</code> · ${mine.length} changes since the previous release.</p></section>` +
        `<section class="day">${[rel, ...mine].map(entryCard).join('\n')}</section><p><a href="/archive/#releases">← All releases</a></p>`
    }))
  }

  // ----- archive (all days + releases + categories)
  const cats = new Map()
  for (const e of entries) cats.set(e.category, (cats.get(e.category) || 0) + 1)
  const catTiles = [...cats.entries()].sort((a, b) => b[1] - a[1]).map(([c, k]) =>
    `<div class="tile"><b>${esc(c)}</b><span>${k} changes</span></div>`).join('')
  const dayLinks = byDay.map(d => `<li><a href="/day/${d.day}/">${esc(d.day)}</a> <span class="muted">${d.entries.length}</span></li>`).join('')
  const relLinks = [...vers].reverse().map(v => `<li><a href="/release/${v.version}/">${esc(v.version)}</a> <span class="muted">${esc(v.date.slice(0, 10))}</span></li>`).join('')
  await write(dist, 'archive/index.html', layout({
    title: 'Archive', path: '/archive/',
    body: `<section class="hero"><h1>Archive</h1><p>Every ${entries.length} tracked changes, ${byDay.length} active days, ${vers.length} releases.</p>
<div class="grid">${catTiles}</div></section>
<h2 id="releases" class="day" style="border-bottom:1px solid var(--line)">Releases</h2><ul>${relLinks}</ul>
<h2 class="day" style="border-bottom:1px solid var(--line)">Days</h2><ul>${dayLinks}</ul>`
  }))

  // ----- search (the only page with JS: tiny client filter over JSON index)
  const idxJson = entries.map(e => ({
    d: e.day, t: (e.ai?.title || e.title || '').slice(0, 90), c: e.category, s: e.sha.slice(0, 12), a: e.significance,
    u: `/day/${e.day}/#${e.sha.slice(0, 12)}`
  }))
  await write(dist, 'search-index.json', JSON.stringify(idxJson))
  await write(dist, 'search/index.html', layout({
    title: 'Search', path: '/search/',
    body: `<section class="hero"><h1>Search ${entries.length} changes</h1><p>Model names, files, commands, releases.</p></section>
<input id="q" type="search" placeholder="e.g. muse spark, slash command, runner…" autocomplete="off">
<div id="hits"></div>
<script>
fetch('/search-index.json').then(r=>r.json()).then(ix=>{let t;const q=document.getElementById('q'),h=document.getElementById('hits');
const go=()=>{const v=q.value.trim().toLowerCase();if(!v){h.innerHTML='';return}
const w=v.split(/\\s+/);const hits=ix.filter(e=>{const s=(e.t+' '+e.c).toLowerCase();return w.every(x=>s.includes(x))}).slice(0,200);
h.innerHTML=hits.map(e=>'<article class="entry"><h3><a href="'+e.u+'">'+e.t+'</a></h3><div class="badges"><span class="badge">'+e.c+'</span><span class="badge">'+e.a+'</span><span class="badge">'+e.d+'</span></div></article>').join('')||'<p class="muted">No matches.</p>'};
q.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(go,120)})})
</script>`
  }))

  // ----- about
  await write(dist, 'about/index.html', layout({
    title: 'About', path: '/about/',
    body: `<section class="hero"><h1>About this changelog</h1>
<div class="summary" style="max-width:70ch">
<p><strong>Why:</strong> Freebuff's public repo is a mirror. A bot pushes "Sync public snapshot" commits from the private repo, and the commit messages say nothing — so the community can't see what changed.</p>
<p><strong>How:</strong> this site analyzes the <em>diff</em> behind every public commit (${entries.length.toLocaleString()} tracked changes from ${esc(changelog.counts?.commitsScanned || '?').toLocaleString()} analyzed commits). Each sync snapshot's diff is usually one focused change, so per-commit entries are highly accurate. A rule-based extractor detects model-catalog edits in the README table, CLI version bumps, new/removed slash commands, added/deleted/renamed files, and informative inline comments. An optional AI pass (cached, one call per commit, from the exact diff text) can rewrite summaries — never inventing beyond the diff.</p>
<p><strong>Updates:</strong> a GitHub Action reruns the analyzer hourly; Cloudflare Pages redeploys automatically. This page you are reading is a pre-rendered static file with zero client JavaScript (except /search), one inline stylesheet, system fonts, and edge caching.</p>
<p><strong>Limitations:</strong> multiple private commits can sometimes land in one public snapshot; internal-only changes are labeled as such. Commit and diff links give you ground truth.</p>
</div></section>`
  }))

  // ----- open PRs page (community activity ahead of merges)
  if (openPrs?.length) {
    const rows = openPrs.map(p => `<li><a href="${esc(p.url)}" rel="noopener">${esc(p.title)}</a>
<span class="muted">#${p.number} by ${esc(p.author)} · ${esc(p.updated.slice(0, 10))} · +${p.additions}/−${p.deletions}${p.draft ? ' · draft' : ''}</span></li>`).join('')
    await write(dist, 'in-flight/index.html', layout({
      title: 'In flight', path: '/in-flight/',
      body: `<section class="hero"><h1>In flight</h1><p>Open community PRs on the Freebuff repo (merged PRs appear here in the changelog the moment they land). Updated ${esc(fmtDateHuman(generated))}.</p></section><ul>${rows}</ul>`
    }))
  }

  // ----- feeds / api
  const feedEntries = entries.filter(e => e.significance !== 'minor').slice(0, 60)
  const items = feedEntries.map(e => {
    const title = e.ai?.title || e.title || deriveTitleSafe(e)
    return `<item><title>${esc(title)}</title><link>${SITE.url}/day/${e.day}/#${e.sha.slice(0, 12)}</link>
<guid isPermaLink="false">${esc(e.sha)}</guid><pubDate>${new Date(e.date).toUTCString()}</pubDate>
<description>${esc(title)} — ${esc((e.ai?.summary || e.summary).replace(/[*`#]/g, ''))}</description></item>`
  }).join('')
  await write(dist, 'feed.xml',
    `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${SITE.name} (unofficial)</title>
<link>${SITE.url}</link><description>${esc(SITE.desc)}</description><language>en</language>${items}</channel></rss>`)

  await write(dist, 'changelog.json', JSON.stringify(changelog))
  await write(dist, 'api/entries.json', JSON.stringify({ generatedAt: generated, head: changelog.headSha, total: entries.length, latest: entries.slice(0, 60) }))

  // ----- sitemap / robots / headers / 404
  const urls = ['/']
  for (const d of byDay) urls.push(`/day/${d.day}/`)
  for (const v of vers) urls.push(`/release/${v.version}/`)
  urls.push('/archive/', '/search/', '/about/', '/in-flight/')
  await write(dist, 'sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u => `<url><loc>${SITE.url}${u}</loc></url>`).join('')}</urlset>`)
  await write(dist, 'robots.txt', `User-agent: *\nAllow: /\nSitemap: ${SITE.url}/sitemap.xml\n`)
  await write(dist, '_headers', `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
/index.html
  Cache-Control: public, max-age=300
/changelog.json
  Cache-Control: public, max-age=300
/search-index.json
  Cache-Control: public, max-age=3600
/feed.xml
  Cache-Control: public, max-age=600
/sitemap.xml
  Cache-Control: public, max-age=86400
/day/
  Cache-Control: public, max-age=86400
/release/
  Cache-Control: public, max-age=86400
`)
  await write(dist, '404.html', layout({ title: 'Not found', path: '/404', body: '<h1>404 — nothing shipped here… yet.</h1><p><a href="/">← Back to the changelog</a></p>' }))

  return { entries: entries.length, days: byDay.length, releases: vers.length }
}
