// generator/lib/site.mjs - renders data/changelog.json into a zero-dependency,
// fully static, subdued/monochrome developer terminal site (system monospace,
// authentic CLI/git-log presentation, dark theme, zero emojis, calm palette).
import { writeText, writeBinary } from './util.mjs'
import { escapeHtml as esc, fmtDateHuman, pool } from './util.mjs'
import { CSS } from './style.mjs'
import { generateFaviconIco, FAVICON_SVG, FEED_XSL, feedItem, feedXml, feedJson, jsonItem, generateIconPng, ogCardSvg } from './feed.mjs'

const SITE = {
  name: 'Freebuff Changelog',
  tagline: 'What actually shipped in Freebuff: reconstructed commit by commit from public diffs.',
  url: process.env.SITE_URL || 'https://freebuff-changelog.nordicnode.workers.dev',
  desc: 'Developer changelog for Freebuff (github.com/CodebuffAI/freebuff). Accurate entries generated by analyzing the git diffs behind every public snapshot.'
}

// ---------------------------------------------------------------------------


function miniMd (text) {
  let s = esc(text)
  s = s.replace(/`([^`]+)`/g, '<code>$1</code>')
  s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2" rel="noopener">$1</a>')
  return s
}

function layout ({ title, path, body, desc, noindex, ogImage }) {
  const abs = (p) => p.startsWith('http') ? p : SITE.url + p
  return `<!doctype html><html lang="en" data-theme="dark"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#0d1117">
<title>${esc(title)} · ${SITE.name}</title>
<meta name="description" content="${esc(desc || SITE.desc)}">
${noindex ? '<meta name="robots" content="noindex">' : ''}
<link rel="canonical" href="${abs(path)}">
<meta property="og:title" content="${esc(title)} · ${SITE.name}">
<meta property="og:description" content="${esc(desc || SITE.desc)}">
<meta property="og:image" content="${abs(ogImage || '/favicon.svg')}">
<meta name="twitter:card" content="summary_large_image">
<meta property="og:type" content="website"><meta property="og:url" content="${abs(path)}">
<link rel="alternate" type="application/rss+xml" title="${SITE.name} (major + notable)" href="${SITE.url}/feed.xml">
<link rel="alternate" type="application/rss+xml" title="${SITE.name} (models only)" href="${SITE.url}/feed-models.xml">
<link rel="alternate" type="application/rss+xml" title="${SITE.name} (releases only)" href="${SITE.url}/feed-releases.xml">
<link rel="alternate" type="application/feed+json" title="${SITE.name} (JSON)" href="${SITE.url}/feed.json">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="apple-touch-icon" href="/icon-192.png">
<style>${CSS}</style></head><body><main>
<header class="top">
  <div class="brand">
    <a class="logo" href="/">
      <span class="term-prompt-sym">&gt;</span>
      <span>${SITE.name}</span>
    </a>
  </div>
  <nav class="term-nav">
    <a href="/about/" class="${path === '/about/' ? 'active' : ''}">/about</a>
    <a href="/models/" class="${path.startsWith('/models/') ? 'active' : ''}">/models</a>
    <a href="/stats/" class="${path.startsWith('/stats/') ? 'active' : ''}">/stats</a>
    <a href="/watch/" class="${path.startsWith('/watch/') ? 'active' : ''}">/watch</a>
    <a href="/archive/" class="${path.startsWith('/archive/') ? 'active' : ''}">/archive</a>
    <a href="/search/" class="${path.startsWith('/search/') ? 'active' : ''}">/search</a>
    <a href="/in-flight/" class="${path.startsWith('/in-flight/') ? 'active' : ''}">/in-flight</a>
    <a href="/feed.xml" class="nav-feed">/rss</a>
  </nav>
</header>
${body}
<footer>
  <div>freebuff-changes :: unofficial public snapshot mirror reconstructed from <a href="https://github.com/CodebuffAI/freebuff" target="_blank" rel="noopener">CodebuffAI/freebuff</a></div>
  <div class="footer-links">
    <a href="/about/">[about]</a>
    <a href="https://github.com/CodebuffAI/freebuff" target="_blank" rel="noopener">[github]</a>
  </div>
</footer>
<script>
function updateSyncTimer() {
  const el = document.querySelector('.sync-val');
  if (!el) return;
  // Freeze when stale: a countdown to a sync that already missed is a lie.
  const ageEl = document.querySelector('.sync-age');
  const ageMin = ageEl && ageEl.dataset.generated
    ? Math.max(0, Math.floor((Date.now() - Date.parse(ageEl.dataset.generated)) / 60000))
    : 0;
  const now = new Date();
  if (now.getUTCMinutes() === 0 || ageMin >= 90) {
    el.textContent = 'syncing…';
    el.style.color = 'var(--term-green)';
    return;
  }
  el.style.color = 'var(--term-cyan)';
  const next = new Date(now);
  next.setUTCSeconds(0, 0);
  next.setUTCHours(next.getUTCHours() + 1);
  next.setUTCMinutes(0);
  const diffSec = Math.max(0, Math.floor((next.getTime() - now.getTime()) / 1000));
  const m = Math.floor(diffSec / 60);
  const s = diffSec % 60;
  el.textContent = m + 'm ' + (s < 10 ? '0' : '') + s + 's';
}
updateSyncTimer();
setInterval(updateSyncTimer, 1000);

function updateSyncAge() {
  const el = document.querySelector('.sync-age');
  if (!el || !el.dataset.generated) return;
  const ageMin = Math.max(0, Math.floor((Date.now() - Date.parse(el.dataset.generated)) / 60000));
  const fresh = ageMin < 90;
  el.textContent = el.textContent.replace(/\\s*\\[.*\\]$/, '') + (fresh ? ' [fresh]' : ' [stale ' + ageMin + 'm]');
  el.style.color = fresh ? 'var(--term-green)' : 'var(--term-amber)';
}
updateSyncAge();

function openHashTarget() {
  const hash = window.location.hash;
  if (!hash || hash.length < 2) return;
  let target = null;
  try { target = document.querySelector(hash); } catch (_) { return; }
  if (!target) {
    // Short-sha links (#abcdef) may not match the full 12-char id prefix.
    const short = hash.slice(1);
    if (/^[0-9a-f]{4,11}$/i.test(short)) {
      target = document.querySelector('[id^="' + short + '"]');
    }
  }
  if (target && target.tagName === 'DETAILS' && target.classList.contains('entry')) {
    target.open = true;
    try { target.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (_) {}
  }
}
window.addEventListener('DOMContentLoaded', openHashTarget);
window.addEventListener('hashchange', openHashTarget);

document.addEventListener('keydown', (e) => {
  if (e.key === '/' && !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)) {
    e.preventDefault();
    const q = document.getElementById('q');
    if (q) { q.focus(); q.select(); }
    else { window.location.href = '/search/'; }
  }
});

function copyDiff(btn) {
  const body = btn.closest('.diff-body');
  const pre = body ? body.querySelector('.diff-pre') : null;
  if (!pre) return;
  const text = pre.innerText;
  navigator.clipboard.writeText(text).then(() => {
    const orig = btn.innerText;
    btn.innerText = '[copied!]';
    setTimeout(() => { btn.innerText = orig; }, 1800);
  });
}

document.addEventListener('click', (ev) => {
  const btn = ev.target.closest ? ev.target.closest('.diff-mode') : null;
  if (!btn) return;
  const viewer = btn.closest('.diff-viewer');
  if (!viewer) return;
  viewer.querySelectorAll('.diff-mode').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  const body = viewer.querySelector('.diff-body');
  if (!body || !body.dataset.raw) return;
  const label = viewer.dataset.sha || ('PR-' + viewer.dataset.pr);
  renderDiff(body, body.dataset.raw, label, viewer.dataset.gh || '', btn.dataset.mode);
});

document.addEventListener('toggle', async (ev) => {
  const el = ev.target;
  if (!el.classList.contains('diff-viewer') || !el.open || el.dataset.loaded) return;
  const sha = el.dataset.sha, pr = el.dataset.pr;
  const body = el.querySelector('.diff-body');
  if ((!sha && !pr) || !body) return;
  if (body.querySelector('.diff-pre')) { el.dataset.loaded = '1'; return; }
  body.innerHTML = '<span class="diff-loading">Loading diff…</span>';
  try {
    let url = sha ? '/diffs/' + sha + '.diff' : '/pr-diffs/' + pr + '.diff';
    if (location.protocol === 'file:') {
      const idx = location.pathname.lastIndexOf('/dist/');
      if (idx !== -1) {
        url = location.pathname.substring(0, idx + 6) + (sha ? 'diffs/' + sha + '.diff' : 'pr-diffs/' + pr + '.diff');
      }
    }
    const res = await fetch(url);
    if (!res.ok) throw new Error('HTTP ' + res.status);
    const text = await res.text();
    el.dataset.loaded = '1';
    const label = sha || ('PR-' + pr);
    const viewUrl = el.dataset.gh || (sha ? 'https://github.com/CodebuffAI/freebuff/commit/' + sha : '');
    renderDiff(body, text, label, viewUrl);
  } catch (err) {
    const ghUrl = el.dataset.gh || (sha ? 'https://github.com/CodebuffAI/freebuff/commit/' + sha : '');
    body.innerHTML = '<div class="diff-notice">Full diff not cached locally. ' + (ghUrl ? '<a href="' + ghUrl + '" target="_blank" rel="noopener">View on GitHub &rarr;</a>' : 'View the PR on GitHub for the full diff.') + '</div>';
  }
}, true);

function renderDiff(container, text, label, ghUrl, mode) {
  mode = mode || 'unified';
  container.dataset.raw = text;
  const lines = text.split(/\\r?\\n/);
  const frag = document.createDocumentFragment();

  const toolbar = document.createElement('div');
  toolbar.className = 'diff-toolbar';
  toolbar.innerHTML = '<span class="diff-toolbar-title">$ git diff ' + label.slice(0, 12) + '^!</span>';

  const actions = document.createElement('div');
  actions.className = 'diff-toolbar-actions';

  const copyBtn = document.createElement('button');
  copyBtn.className = 'diff-copy-btn';
  copyBtn.textContent = '[copy diff]';
  copyBtn.onclick = () => copyDiff(copyBtn);
  actions.appendChild(copyBtn);

  if (ghUrl) {
    const ghLink = document.createElement('a');
    ghLink.className = 'diff-gh-btn';
    ghLink.href = ghUrl;
    ghLink.target = '_blank';
    ghLink.rel = 'noopener';
    ghLink.textContent = '[github]';
    actions.appendChild(ghLink);
  }

  toolbar.appendChild(actions);
  frag.appendChild(toolbar);

  if (mode === 'split') {
    // Before/after columns: pair runs of - lines with following + runs.
    const table = document.createElement('table');
    table.className = 'diff-split';
    const addCell = (tr, cls, txt) => {
      const td = document.createElement('td');
      td.className = 'diff-cell ' + cls;
      td.textContent = txt;
      tr.appendChild(td);
    };
    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      if (line.startsWith('diff --git') || line.startsWith('index ') || line.startsWith('@@') || line.startsWith('+++') || line.startsWith('---')) {
        const tr = document.createElement('tr');
        const td = document.createElement('td');
        td.colSpan = 2;
        td.className = 'diff-cell diff-hdr';
        td.textContent = line;
        tr.appendChild(td);
        table.appendChild(tr);
        i++;
        continue;
      }
      if (line.startsWith('-') && !line.startsWith('---')) {
        const dels = [];
        while (i < lines.length && lines[i].startsWith('-') && !lines[i].startsWith('---')) { dels.push(lines[i].slice(1)); i++; }
        const adds = [];
        while (i < lines.length && lines[i].startsWith('+') && !lines[i].startsWith('+++')) { adds.push(lines[i].slice(1)); i++; }
        const n = Math.max(dels.length, adds.length);
        for (let k = 0; k < n; k++) {
          const tr = document.createElement('tr');
          addCell(tr, 'diff-del', dels[k] ?? '');
          addCell(tr, 'diff-add', adds[k] ?? '');
          table.appendChild(tr);
        }
        continue;
      }
      if (line.startsWith('+') && !line.startsWith('+++')) {
        const tr = document.createElement('tr');
        addCell(tr, 'diff-del', '');
        addCell(tr, 'diff-add', line.slice(1));
        table.appendChild(tr);
        i++;
        continue;
      }
      const tr = document.createElement('tr');
      const ctx = line.startsWith(' ') ? line.slice(1) : line;
      addCell(tr, 'diff-ctx', ctx);
      addCell(tr, 'diff-ctx', ctx);
      table.appendChild(tr);
      i++;
    }
    frag.appendChild(table);
    container.innerHTML = '';
    container.appendChild(frag);
    return;
  }

  const pre = document.createElement('pre');
  pre.className = 'diff-pre';
  for (const line of lines) {
    const row = document.createElement('div');
    row.className = 'diff-line';
    const marker = document.createElement('span');
    marker.className = 'diff-marker';
    const textSpan = document.createElement('span');
    textSpan.className = 'diff-text';
    
    if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('diff --git') || line.startsWith('index ')) {
      row.classList.add('diff-hdr');
      marker.textContent = ' ';
      textSpan.textContent = line;
    } else if (line.startsWith('+')) {
      row.classList.add('diff-add');
      marker.textContent = '+';
      textSpan.textContent = line.slice(1);
    } else if (line.startsWith('-')) {
      row.classList.add('diff-del');
      marker.textContent = '−';
      textSpan.textContent = line.slice(1);
    } else if (line.startsWith('@@')) {
      row.classList.add('diff-hunk');
      marker.textContent = ' ';
      textSpan.textContent = line;
    } else {
      marker.textContent = ' ';
      textSpan.textContent = line.startsWith(' ') ? line.slice(1) : line;
    }
    row.appendChild(marker);
    row.appendChild(textSpan);
    pre.appendChild(row);
  }
  frag.appendChild(pre);

  container.innerHTML = '';
  container.appendChild(frag);
}
</script>
</body></html>`
}

function badges (e) {
  const b = []
  if (e.significance === 'major') b.push('<span class="badge maj">[MAJOR]</span>')
  else if (e.significance === 'notable') b.push('<span class="badge not">[NOTABLE]</span>')
  if (e.modelChanges) b.push('<span class="badge model">[MODEL]</span>')
  if (e.version) b.push(`<a class="badge ver" href="/release/${e.version}/" onclick="event.stopPropagation()">[v${e.version}]</a>`)
  if (e.kind === 'community' && e.pr) b.push(`<span class="badge">[PR #${e.pr}]</span>`)
  b.push(`<span class="badge cat">[${esc(e.category)}]</span>`)
  return b.join('')
}

function modelDiffLine (e) {
  if (!e.modelChanges) return ''
  const { added = [], removed = [] } = e.modelChanges
  const tables = e.modelChanges.tables || {}
  const pillsFor = (names, cls, sign) => names.map(m => {
    const row = tables[m]?.after || tables[m]?.before
    const tip = row ? ` title="${esc(row.join(' · '))}"` : ''
    return `<span class="${cls}"${tip}>${sign}${esc(m)}</span>`
  }).join('<span class="model-sep">,</span> ')
  const addHtml = pillsFor(added, 'modelplus', '+')
  const remHtml = pillsFor(removed, 'modelminus', '−')
  let swapContent = ''
  if (added.length && removed.length) {
    swapContent = `${addHtml} <span class="swap-arrow">-></span> ${remHtml}`
  } else {
    swapContent = [addHtml, remHtml].filter(Boolean).join(' ')
  }
  // Snapshot embed: full before/after README rows for the changed models,
  // so readers see access + best-for without opening the diff.
  const snapRows = [...added.map(m => [m, 'add']), ...removed.map(m => [m, 'del'])]
    .map(([m, kind]) => {
      const row = tables[m]?.after || tables[m]?.before
      if (!row) return ''
      return `<div class="snap-row ${kind}"><span class="snap-name">${esc(m)}</span><span class="snap-cells">${esc(row.slice(1).join(' · ') || row[0])}</span></div>`
    }).join('')
  const snap = snapRows ? `<div class="model-snap">${snapRows}</div>` : ''
  return `<div class="model-swap"><span class="model-swap-tag">MODEL SWAP:</span> <span class="model-swap-pills">${swapContent}</span></div>${snap}`
}

function shortPath (p) {
  if (p.length <= 36) return p
  const parts = p.split('/')
  if (parts.length > 2) return parts[0] + '/…/' + parts.at(-1)
  return p.slice(0, 16) + '…' + p.slice(-14)
}

function fileChips (e) {
  const chips = []
  const totalListed = (e.files.added?.length || 0) + (e.files.removed?.length || 0) + (e.files.modified?.length || 0)
  const shownAdded = (e.files.added || []).slice(0, 3), shownRemoved = (e.files.removed || []).slice(0, 3)
  const modCap = shownAdded.length + shownRemoved.length ? 3 : 5
  const shownModified = (e.files.modified || []).slice(0, modCap)
  for (const p of shownAdded) chips.push(`<span class="fchip add" title="${esc(p)}">${esc(shortPath(p))}</span>`)
  for (const p of shownRemoved) chips.push(`<span class="fchip del" title="${esc(p)}">${esc(shortPath(p))}</span>`)
  for (const p of shownModified) chips.push(`<span class="fchip mod" title="${esc(p)}">${esc(shortPath(p))}</span>`)
  const shown = shownAdded.length + shownRemoved.length + shownModified.length
  const extra = Math.max(totalListed - shown, (e.files.meaningful || 0) - shown)
  if (extra > 0) chips.push(`<span class="fchip more">+${extra} more</span>`)
  return chips.length ? `<div class="files">${chips.join('')}</div>` : ''
}

// Related entries: same category, newest first, excluding self. Precomputed
// per build into a lookup so cards render without scanning 7k entries.
export function buildRelatedIndex (entries, n = 3) {
  const byCat = new Map()
  for (const e of entries) {
    if (!byCat.has(e.category)) byCat.set(e.category, [])
    byCat.get(e.category).push(e)
  }
  const idx = new Map()
  for (const e of entries) {
    idx.set(e.sha, (byCat.get(e.category) || []).filter(x => x.sha !== e.sha).slice(0, n))
  }
  return idx
}

function relatedLine (e, relatedIdx) {
  const rel = relatedIdx?.get(e.sha) || []
  if (!rel.length) return ''
  return `<div class="related">RELATED: ${rel.map(r => `<a href="/day/${r.day}/#${r.sha.slice(0, 12)}">${esc((r.ai?.title || r.title || '').slice(0, 60))}</a>`).join(' · ')}</div>`
}

function entryCard (e, isExpanded = false, mode = 'full', relatedIdx = null) {
  const time = e.date.slice(11, 16)
  const anchor = e.sha.slice(0, 12)
  const title = e.ai?.title ? esc(e.ai.title) : esc(e.title || deriveTitleSafe(e))
  if (mode === 'teaser') {
    // Lightweight homepage row: title + facts only, linking to the full
    // card on the day page. A plain article (not <details>) so it never
    // pretends to expand with nothing to show.
    const factLine = e.facts?.length ? `<div class="teaser-facts">${e.facts.length} key fact${e.facts.length === 1 ? '' : 's'} &middot; +${e.stats.additions} / −${e.stats.deletions}</div>` : ''
    return `<article class="entry teaser ${e.significance}" id="${anchor}">
  <div class="entry-meta-top">
    <span class="commit-ref">commit <a href="/day/${e.day}/#${anchor}">${anchor}</a></span>
    <span class="entry-utc">${esc(time)} UTC</span>
    <div class="badges">${badges(e)}</div>
    <a class="permalink" href="/day/${e.day}/#${anchor}" title="Permalink" aria-label="Permalink">#</a>
  </div>
  <h3 class="entry-title"><a href="/day/${e.day}/#${anchor}">${title}</a></h3>
  ${factLine}
</article>`
  }
  // Diffs lazy-load in the browser on toggle (fetch /diffs/<sha>.diff),
  // so the server never holds diff text in memory or bloats pages with it.
  // Compare view renders the fetched diff side-by-side inline on demand.
  let diffViewer = ''
  if (e.kind === 'sync') {
    diffViewer = `<details class="diff-viewer" data-sha="${e.sha}" data-gh="${esc(e.compareUrl || e.url || '')}">
<summary class="diff-toggle">
  <span class="diff-toggle-left">
    <span class="diff-arrow">&gt;</span>
    <span>View inline diff</span>
  </span>
  <span class="diff-badge">+${e.stats.additions} / −${e.stats.deletions}</span>
</summary>
<div class="diff-view-modes"><button class="diff-mode active" data-mode="unified">unified</button><button class="diff-mode" data-mode="split">split</button></div>
<div class="diff-body"><span class="diff-loading">Loading diff…</span></div>
</details>`
  }
  return `<details class="entry ${e.significance}" id="${anchor}"${isExpanded ? ' open' : ''}>
<summary class="entry-summary">
  <div class="entry-meta-top">
    <span class="entry-arrow">&gt;</span>
    <span class="commit-ref">commit <a href="https://github.com/CodebuffAI/freebuff/commit/${e.sha}" target="_blank" rel="noopener" onclick="event.stopPropagation()">${anchor}</a></span>
    <span class="entry-utc">${esc(time)} UTC</span>
    <div class="badges">${badges(e)}</div>
    <a class="permalink" href="/day/${e.day}/#${anchor}" title="Permalink" aria-label="Permalink" onclick="event.stopPropagation()">#</a>
  </div>
  <h3 class="entry-title">${title}</h3>
</summary>
<div class="entry-body">
${modelDiffLine(e)}
<div class="summary">${miniMd(e.ai?.summary || e.summary)}</div>
${e.facts?.length ? `<ul class="facts">${e.facts.slice(0, 3).map(f => `<li>${miniMd(f)}</li>`).join('')}</ul>` : ''}
${fileChips(e)}
${diffViewer}
${relatedLine(e, relatedIdx)}
<div class="metarow">
  <span class="diffstat"><b>+${e.stats.additions}</b> / <i>−${e.stats.deletions}</i> &middot; ${e.files.total} file${e.files.total === 1 ? '' : 's'}</span>
  <div class="meta-links">
    ${e.sourceSha ? `<a class="meta-link" href="https://github.com/CodebuffAI/freebuff/commit/${e.sha}" rel="noopener" target="_blank">snapshot</a>` : ''}
    ${e.pr ? `<a class="meta-link" href="${esc(e.prUrl || '')}" rel="noopener" target="_blank">PR #${e.pr}</a>` : ''}
    ${e.compareUrl ? `<a class="meta-link" href="${esc(e.compareUrl)}" rel="noopener" target="_blank">compare</a>` : e.url ? `<a class="meta-link" href="${esc(e.url)}" rel="noopener" target="_blank">commit</a>` : ''}
  </div>
</div>
</div>
</details>`
}

function deriveTitleSafe (e) {
  return (e.summary || '').split(/[.:]/)[0].slice(0, 70) || `${e.category} update`
}

// Search ranking (mirrored client-side): title hits beat category hits,
// significance boosts, recency breaks ties. Exported for unit tests.
export function scoreHit (title, cat, sig, day, words) {
  const t = title.toLowerCase(), c = cat.toLowerCase()
  let s = 0
  for (const w of words) {
    if (t.includes(w)) s += w.length > 4 ? 3 : 2
    else if (c.includes(w)) s += 1
    else return -1
  }
  if (sig === 'major') s += 2
  else if (sig === 'notable') s += 1
  return s
}

export function modelSlug (name) {
  const base = String(name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'model'
  return base
}

function groupByDay (entries) {
  const out = []
  let cur = null
  for (const e of entries) {
    if (!cur || cur.day !== e.day) { cur = { day: e.day, entries: [] }; out.push(cur) }
    cur.entries.push(e)
  }
  return out
}

// Replay model catalog changes oldest-first: current lineup vs retired.
export function modelTimeline (modelEntries) {
  const chrono = [...modelEntries].sort((a, b) => a.date < b.date ? -1 : a.date > b.date ? 1 : (a.sha < b.sha ? -1 : 1))
  const live = new Set(), retired = new Set()
  for (const e of chrono) {
    for (const a of (e.modelChanges?.added || [])) { live.add(a); retired.delete(a) }
    for (const r of (e.modelChanges?.removed || [])) { live.delete(r); retired.add(r) }
  }
  return { chrono: chrono.reverse(), live: [...live].sort(), retired: [...retired].sort() }
}


async function write (dist, p, html) { await writeText(`${dist.replace(/\/$/, '')}/${p}`, html) }

export async function buildSite ({ changelog, openPrs, dist }) {
  const entries = [...changelog.entries].reverse() // newest first
  const byDay = groupByDay(entries)
  const relatedIdx = buildRelatedIndex(entries)
  const modelEntries = entries.filter(e => e.modelChanges)
  const releases = entries.filter(e => e.version)
  const first = entries.at(-1), last = entries[0]
  const generated = changelog.generatedAt
  const scannedCount = changelog.counts?.commitsScanned || entries.length

  // ----- index: newest days worth of entries
  const NEW_WINDOW = 90
  const idx = []
  let n = 0
  for (const d of byDay) { if (n >= NEW_WINDOW) break; idx.push(d); n += d.entries.length }
  const hero = `
<section class="hero">
  <div class="term-box term-box-slim">
    <div class="term-box-hdr">
      <span class="term-box-title">LATEST :: ${esc(first.day)} &rarr; ${esc(last.day)}</span>
      <span>${entries.length.toLocaleString()} changes &middot; ${releases.length} releases</span>
    </div>
    <div class="term-footer-bar">
      <span>HEAD: <a href="https://github.com/CodebuffAI/freebuff/commit/${esc(changelog.headSha || '')}" target="_blank" rel="noopener">${esc((changelog.headSha || '').slice(0, 10))}</a> &middot; updated <span class="sync-age" data-generated="${esc(generated)}">${esc(fmtDateHuman(generated))} UTC</span></span>
      <span>NEXT SYNC: <span class="sync-val" style="color:var(--term-cyan);font-weight:600">--:--</span></span>
    </div>
  </div>
</section>`

  let isFirstIndex = true
  const daysHtml = idx.map((d, di) =>
    `<section class="day" id="${d.day}">
<div class="day-line">
  <h2><time datetime="${d.day}">[ ${esc(fmtDateHuman(d.day))} ]</time></h2>
  <span class="day-count">${d.entries.length} change${d.entries.length === 1 ? '' : 's'}</span>
</div>
${d.entries.map(e => {
  const open = isFirstIndex
  isFirstIndex = false
  // Homepage weight: full bodies only for the first day; older entries
  // collapse to title + facts (full body lives on the day page).
  return entryCard(e, open, di === 0 ? 'full' : 'teaser', relatedIdx)
}).join('\n')}</section>`).join('')

  await write(dist, 'index.html', layout({ title: 'Home', path: '/', body: hero + daysHtml +
    `<div class="pager"><a href="/archive/">[ full archive &rarr; ]</a><a href="/feed.xml">[ rss ]</a><a href="/feed-models.xml">[ models rss ]</a><a href="/feed-releases.xml">[ releases rss ]</a></div>` }))

  // ----- per-day pages (independent writes: bounded parallel pool)
  const dayOptions = byDay.map(d => `<option value="/day/${d.day}/">${esc(fmtDateHuman(d.day))} (${d.entries.length})</option>`).join('')
  const dayJump = (current) => `<form class="day-jump" action="/day/${current}/" method="get" onsubmit="location.href=this.d.value;return false"><label>JUMP:<select name="d" onchange="if(this.value)location.href=this.value"><option value="">--pick a date--</option>${dayOptions}</select></label></form>`
  const dayTasks = byDay.map((d, i) => async () => {
    const prevDay = i < byDay.length - 1 ? byDay[i + 1] : null
    const nextDay = i > 0 ? byDay[i - 1] : null
    const dayPager = `<div class="pager">` +
      (prevDay ? `<a href="/day/${prevDay.day}/">&larr; ${esc(fmtDateHuman(prevDay.day))}</a>` : '<span></span>') +
      dayJump(d.day) +
      (nextDay ? `<a href="/day/${nextDay.day}/">${esc(fmtDateHuman(nextDay.day))} &rarr;</a>` : '<span></span>') +
      `</div>`
    await write(dist, `day/${d.day}/index.html`, layout({
      title: fmtDateHuman(d.day), path: `/day/${d.day}/`,
      desc: `${d.entries.length} Freebuff changes on ${d.day}`,
      ogImage: `/og/${d.day}.svg`,
      body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">DAILY_LOG :: ${esc(d.day)}</span><span>${d.entries.length} entries</span></div><p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">Reconstructed public snapshot commits pushed to CodebuffAI/freebuff on this date.</p></div></section>` +
        dayPager +
        `<section class="day">${d.entries.map((e, entryIdx) => entryCard(e, entryIdx === 0, 'full', relatedIdx)).join('\n')}</section>` +
        dayPager +
        `<p style="margin-top:20px;font-size:.82rem"><a href="/">&larr; [latest]</a> &middot; <a href="/archive/">[archive]</a></p>`
    }))
    const ogTitles = d.entries.slice(0, 3).map(e => e.ai?.title || e.title || '')
    await write(dist, `og/${d.day}.svg`, ogCardSvg(fmtDateHuman(d.day), ogTitles, `${d.entries.length} changes`))
  })
  await pool(dayTasks, 16)

  // ----- release pages (ranges precomputed once, pages written in parallel)
  const verMap = new Map()
  for (const e of releases) verMap.set(e.version, e)
  const vers = [...verMap.values()]
  vers.sort((a, b) => a.date < b.date ? -1 : 1)
  const relRanges = vers.map((rel, i) => {
    const lo = i > 0 ? vers[i - 1].date : '0000'
    return entries.filter(e => e.date > lo && e.date <= rel.date && e.sha !== rel.sha)
  })
  await pool(vers.map((rel, i) => async () => {
    const mine = relRanges[i]
    const prevRel = i > 0 ? vers[i - 1] : null
    const nextRel = i < vers.length - 1 ? vers[i + 1] : null
    const relPager = `<div class="pager">` +
      (prevRel ? `<a href="/release/${prevRel.version}/">&larr; v${esc(prevRel.version)}</a>` : '<span></span>') +
      (nextRel ? `<a href="/release/${nextRel.version}/">v${esc(nextRel.version)} &rarr;</a>` : '<span></span>') +
      `</div>`
    await write(dist, `release/${rel.version}/index.html`, layout({
      title: `Release ${rel.version}`, path: `/release/${rel.version}/`,
      desc: `Freebuff v${rel.version}: ${mine.length} changes since the previous release.`,
      body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">RELEASE_TAG :: v${esc(rel.version)}</span><span>${esc(rel.date.slice(0, 10))}</span></div><p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">Freebuff v${esc(rel.version)} &middot; commit <code>${rel.sha.slice(0, 10)}</code> &middot; ${mine.length} commits since previous release.</p></div></section>` +
        relPager +
        `<section class="day">${[rel, ...mine].map((e, entryIdx) => entryCard(e, entryIdx === 0, 'full', relatedIdx)).join('\n')}</section>` +
        relPager +
        `<p style="margin-top:20px;font-size:.82rem"><a href="/archive/#releases">&larr; [all releases]</a> &middot; <a href="/">[latest]</a></p>`
    }))
  }), 16)

  // ----- models timeline (catalog history: current lineup, retired, per-change rows)
  const { chrono: modelChrono, live: modelLive, retired: modelRetired } = modelTimeline(modelEntries)
  const modelLink = (m, cls, sign) => `<a class="${cls}" href="/models/${modelSlug(m)}/">${sign}${esc(m)}</a>`
  const titleOfModel = (e) => e.ai?.title || e.title || deriveTitleSafe(e)
  const modelRows = modelChrono.map(e => {
    const { added = [], removed = [] } = e.modelChanges || {}
    const addHtml = added.map(m => modelLink(m, 'modelplus', '+')).join('<span class="model-sep">,</span> ')
    const remHtml = removed.map(m => modelLink(m, 'modelminus', '−')).join('<span class="model-sep">,</span> ')
    const swap = added.length && removed.length
      ? `${addHtml} <span class="swap-arrow">-&gt;</span> ${remHtml}`
      : [addHtml, remHtml].filter(Boolean).join(' ')
    return `<div class="model-row">
  <span class="model-row-date"><a href="/day/${e.day}/#${e.sha.slice(0, 12)}">${esc(e.day)}</a></span>
  <span class="model-row-change">${swap}</span>
  <span class="model-row-title">${esc(e.ai?.title || e.title || '')}</span>
</div>`
  }).join('')
  await write(dist, 'models/index.html', layout({
    title: 'Models', path: '/models/',
    desc: `Free model catalog history: ${modelLive.length} live, ${modelRetired.length} retired across ${modelChrono.length} changes.`,
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">MODEL_LINEUP :: free picker catalog</span>
      <span>${modelLive.length} live &middot; ${modelRetired.length} retired</span>
    </div>
    <div style="font-size:.76rem;color:var(--txt-dim);margin-bottom:6px">LIVE:</div>
    <div class="model-lineup">${modelLive.map(m => modelLink(m, 'modelplus', '')).join('<span class="model-sep">,</span> ')}</div>
    ${modelRetired.length ? `<div style="font-size:.76rem;color:var(--txt-dim);margin:10px 0 6px">RETIRED:</div>
    <div class="model-lineup">${modelRetired.map(m => modelLink(m, 'modelminus', '')).join('<span class="model-sep">,</span> ')}</div>` : ''}
    <p style="margin:10px 0 0;font-size:.78rem;color:var(--txt-dim)">SUBSCRIBE: <a href="/feed-models.xml">[models rss]</a> &middot; <a href="/feed.xml">[all changes]</a> &middot; per-model feeds on each model page</p>
  </div>
</section>
<div class="section-hdr">
  <h2>== CATALOG HISTORY (${modelChrono.length} CHANGES) ==</h2>
</div>
<div class="model-history">${modelRows}</div>`
  }))

  // ----- per-model pages (one page per catalog name: status, events, watch feed)
  const byModel = new Map()
  for (const e of modelChrono) {
    for (const m of (e.modelChanges?.added || [])) {
      if (!byModel.has(m)) byModel.set(m, [])
      byModel.get(m).push({ e, kind: 'added' })
    }
    for (const m of (e.modelChanges?.removed || [])) {
      if (!byModel.has(m)) byModel.set(m, [])
      byModel.get(m).push({ e, kind: 'removed' })
    }
  }
  const liveSet = new Set(modelLive)
  await pool([...byModel.entries()].map(([name, events]) => async () => {
    const slug = modelSlug(name)
    const status = liveSet.has(name) ? 'LIVE' : 'RETIRED'
    const firstSeen = events[events.length - 1].e.day
    const lastSeen = events[0].e.day
    const rows = events.map(({ e, kind }) => {
      const row = e.modelChanges?.tables?.[name]
      const cells = row ? (row.after || row.before) : null
      const detail = cells ? `<span class="snap-cells">${esc(cells.slice(1).join(' · ') || cells[0])}</span>` : ''
      return `<div class="model-row"><span class="model-row-date"><a href="/day/${e.day}/#${e.sha.slice(0, 12)}">${esc(e.day)}</a></span>`
        + `<span class="model-row-change">${kind === 'added' ? '<span class="modelplus">+added</span>' : '<span class="modelminus">−removed</span>'}</span>`
        + `<span class="model-row-title">${esc(e.ai?.title || e.title || '')} ${detail}</span></div>`
    }).join('')
    const evts = events.map(({ e }) => e)
    await write(dist, `models/${slug}/feed.xml`, feedXml(SITE.url, SITE.name, SITE.desc, generated, `models/${slug}/feed.xml`, `${SITE.name}: ${name} (unofficial)`, `Catalog events for ${name}: additions, retirements, swaps.`, evts.map(e => feedItem(SITE.url, e, titleOfModel)).join('')))
    await write(dist, `models/${slug}/index.html`, layout({
      title: name, path: `/models/${slug}/`,
      desc: `${name} is ${status.toLowerCase()} in the Freebuff free picker: ${events.length} catalog events, ${firstSeen} to ${lastSeen}.`,
      body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">MODEL :: ${esc(name)}</span><span class="${status === 'LIVE' ? 'modelplus' : 'modelminus'}">[${status}]</span></div>`
        + `<p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">${events.length} catalog event${events.length === 1 ? '' : 's'} &middot; ${esc(firstSeen)} &rarr; ${esc(lastSeen)} &middot; <a href="/models/">[all models]</a> &middot; <a href="/models/${slug}/feed.xml">[watch rss]</a></p></div></section>`
        + `<div class="section-hdr"><h2>== HISTORY (${events.length}) ==</h2></div><div class="model-history">${rows}</div>`
    }))
  }), 8)

  // ----- archive (all days + releases + categories)
  const cats = new Map()
  for (const e of entries) cats.set(e.category, (cats.get(e.category) || 0) + 1)
  const catTiles = [...cats.entries()].sort((a, b) => b[1] - a[1]).map(([c, k]) =>
    `<a class="tile" href="/search/?q=${encodeURIComponent(c)}"><b>${esc(c)}</b><span>${k.toLocaleString()} changes</span></a>`).join('')
  
  const relCards = [...vers].reverse().map(v =>
    `<div class="release-card"><a href="/release/${v.version}/">v${esc(v.version)}</a><span style="font-size:.74rem;color:var(--txt-subtle)">${esc(v.date.slice(0, 10))}</span></div>`
  ).join('')

  const years = new Map()
  for (const d of byDay) {
    const y = d.day.slice(0, 4)
    const m = d.day.slice(0, 7)
    if (!years.has(y)) years.set(y, new Map())
    const months = years.get(y)
    if (!months.has(m)) months.set(m, [])
    months.get(m).push(d)
  }
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const yearSections = [...years.entries()].map(([y, months]) => {
    const monthHtml = [...months.entries()].map(([m, days]) => {
      const [, mo] = m.split('-')
      const name = monthNames[Number(mo) - 1]
      const dayItems = days.map(d => `<li><a href="/day/${d.day}/"><span>${d.day.slice(8)}</span><span style="font-size:.7rem;color:var(--txt-subtle)">${d.entries.length}</span></a></li>`).join('')
      return `<h4 class="archive-month">${name} ${y}</h4><ul class="archive-days">${dayItems}</ul>`
    }).join('')
    return `<h3 class="archive-year">${y}</h3>${monthHtml}`
  }).join('')

  await write(dist, 'archive/index.html', layout({
    title: 'Archive', path: '/archive/',
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">ARCHIVE_INDEX :: historical directory</span>
      <span>${entries.length.toLocaleString()} total commits</span>
    </div>
    <div style="font-size:.76rem;color:var(--txt-subtle);margin-bottom:6px">CATEGORIES:</div>
    <details class="cat-collapse" open><summary class="cat-toggle">[${cats.size} categories — toggle]</summary><div class="grid">${catTiles}</div></details>
  </div>
</section>
<div class="section-hdr">
  <h2 id="releases">== RELEASES (${vers.length}) ==</h2>
</div>
<div class="release-grid">${relCards}</div>
<div class="section-hdr">
  <h2>== DAYS BY MONTH (${byDay.length} DATES) ==</h2>
</div>
${yearSections}`
  }))

  // ----- stats (counts, churn, cadence: zero-dependency CSS bars + SVG sparklines)
  // Sparkline: inline SVG trend (history, not snapshot).
  const spark = (vals, w = 220, h = 36) => {
    const max = Math.max(1, ...vals)
    const pts = vals.map((v, i) => `${(i / Math.max(1, vals.length - 1) * w).toFixed(1)},${(h - 3 - (v / max) * (h - 6)).toFixed(1)}`).join(' ')
    return `<svg class="spark" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="trend: ${vals.join(', ')}"><polyline points="${pts}" fill="none" stroke="var(--term-cyan)" stroke-width="1.5"/></svg>`
  }
  const statCats = [...cats.entries()].sort((a, b) => b[1] - a[1])
  const catMax = statCats[0]?.[1] || 1
  // Per-category monthly history for trend sparklines.
  const catMonths = new Map()
  for (const e of entries) {
    const m = (e.day || '').slice(0, 7)
    if (!catMonths.has(e.category)) catMonths.set(e.category, new Map())
    const cm = catMonths.get(e.category)
    cm.set(m, (cm.get(m) || 0) + 1)
  }
  const allMonths = [...new Set(entries.map(e => (e.day || '').slice(0, 7)))].sort().slice(-12)
  const catSpark = (c) => {
    const cm = catMonths.get(c) || new Map()
    return spark(allMonths.map(m => cm.get(m) || 0), 120, 22)
  }
  const churnByArea = new Map()
  for (const e of entries) {
    const a = (e.areas || [])[0] || 'Repo'
    const c = churnByArea.get(a) || { add: 0, del: 0 }
    c.add += e.stats?.additions || 0
    c.del += e.stats?.deletions || 0
    churnByArea.set(a, c)
  }
  const churnRows = [...churnByArea.entries()].sort((a, b) => (b[1].add + b[1].del) - (a[1].add + a[1].del)).slice(0, 10)
  const churnMax = Math.max(1, ...churnRows.map(([, c]) => c.add + c.del))
  const byMonth = new Map()
  for (const d of byDay) {
    const m = d.day.slice(0, 7)
    byMonth.set(m, (byMonth.get(m) || 0) + d.entries.length)
  }
  const monthRows = [...byMonth.entries()].sort().slice(-12)
  const monthMax = Math.max(1, ...monthRows.map(([, n]) => n))
  const cadenceSpark = spark(monthRows.map(([, n]) => n))
  const modelCounts = new Map()
  for (const e of modelEntries) {
    for (const m of [...(e.modelChanges?.added || []), ...(e.modelChanges?.removed || [])]) {
      modelCounts.set(m, (modelCounts.get(m) || 0) + 1)
    }
  }
  const modelRows2 = [...modelCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12)
  const modelMax = Math.max(1, ...modelRows2.map(([, n]) => n))
  const bar = (lbl, n, max, href, trend) => `<div class="stat-bar-row"><span class="stat-bar-lbl">${href ? `<a href="${href}">${esc(lbl)}</a>` : esc(lbl)}</span><span class="stat-bar"><span class="stat-bar-fill" style="width:${Math.max(2, Math.round(n / max * 100))}%"></span></span><span class="stat-bar-n">${n.toLocaleString()}</span>${trend || ''}</div>`
  await write(dist, 'stats/index.html', layout({
    title: 'Stats', path: '/stats/',
    desc: `Freebuff changelog stats: ${entries.length} changes across ${byDay.length} days, ${vers.length} releases, ${modelEntries.length} model changes.`,
    body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">TELEMETRY :: changelog stats</span><span>${entries.length.toLocaleString()} changes &middot; ${byDay.length} days</span></div>`
      + `<p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">Where the work lands, how fast it ships, and which models churn. Recomputed on every sync.</p></div></section>`
      + `<div class="stat-grid">`
      + `<div class="stat-card"><h3>CHANGES BY CATEGORY (12-MO TREND)</h3>${statCats.map(([c, n]) => bar(c, n, catMax, `/search/?cat=${encodeURIComponent(c)}`, catSpark(c))).join('')}</div>`
      + `<div class="stat-card"><h3>CODE CHURN BY AREA (+/-)</h3>${churnRows.map(([a, c]) => bar(`${a} +${(c.add / 1000).toFixed(0)}k/-${(c.del / 1000).toFixed(0)}k`, c.add + c.del, churnMax)).join('')}</div>`
      + `<div class="stat-card"><h3>SHIPPING CADENCE (LAST 12 MO)</h3>${cadenceSpark}${monthRows.map(([m, n]) => bar(m, n, monthMax, `/archive/`)).join('')}</div>`
      + `<div class="stat-card"><h3>MOST-CHANGED MODELS</h3>${modelRows2.map(([m, n]) => bar(m, n, modelMax, `/models/${modelSlug(m)}/`)).join('')}</div>`
      + `</div>`
  }))

  // ----- search (compact index: field codes + category/sig codebooks)
  // c/s/a as small ints keep the 7k-entry payload lean for Workers egress.
  const SEARCH_CATS = [...new Set(entries.map(e => e.category))].sort()
  const SEARCH_SIGS = ['minor', 'notable', 'major']
  const idxJson = entries.map(e => ([
    e.day,
    (e.ai?.title || e.title || deriveTitleSafe(e)).slice(0, 90),
    SEARCH_CATS.indexOf(e.category),
    e.sha.slice(0, 12),
    SEARCH_SIGS.indexOf(e.significance)
  ]))
  await write(dist, 'search-index.json', JSON.stringify({ cats: SEARCH_CATS, sigs: SEARCH_SIGS, ix: idxJson }))
  await write(dist, 'search/index.html', layout({
    title: 'Search', path: '/search/',
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">QUERY_ENGINE :: Freebuff Changelog</span>
      <span>${entries.length.toLocaleString()} indexed entries</span>
    </div>
    <div class="search-input-row">
      <span class="search-prompt">$ grep -i</span>
      <input id="q" type="search" placeholder="regex / pattern (e.g. muse, claude, CLI, release)..." autocomplete="off" autofocus>
      <span class="search-hint">[press / to focus]</span>
    </div>
    <div class="filter-chips">
      <span class="filter-lbl">FLAGS:</span>
      <button class="filter-chip active" data-filter="">--all</button>
      <button class="filter-chip" data-filter="model">--models</button>
      <button class="filter-chip" data-filter="major">--major</button>
      <button class="filter-chip" data-filter="release">--releases</button>
      <button class="filter-chip" data-filter="CLI">--cli</button>
      <button class="filter-chip" data-filter="prompt">--prompt</button>
      <button class="filter-chip" data-filter="desktop">--desktop</button>
    </div>
    <div class="filter-row">
      <label class="filter-sel-lbl">CATEGORY:
        <select id="fcat">
          <option value="">--all categories</option>
          ${SEARCH_CATS.map(c => `<option value="${esc(c)}">${esc(c)}</option>`).join('')}
        </select>
      </label>
      <label class="filter-sel-lbl">IMPACT:
        <select id="fsig">
          <option value="">--any impact</option>
          ${SEARCH_SIGS.map(s => `<option value="${esc(s)}">${esc(s)}</option>`).join('')}
        </select>
      </label>
    </div>
    <div class="search-status"><span id="match-count"></span></div>
  </div>
</section>

<div id="hits"></div>

<script>
fetch('/search-index.json').then(r=>r.json()).then(({ cats, sigs, ix })=>{
  let t;
  const q = document.getElementById('q'), h = document.getElementById('hits'), cnt = document.getElementById('match-count');
  const chips = document.querySelectorAll('.filter-chip');
  const fcat = document.getElementById('fcat'), fsig = document.getElementById('fsig');
  const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

  const go = () => {
    const v = q.value.trim().toLowerCase();
    const cat = fcat ? fcat.value : '', sig = fsig ? fsig.value : '';
    const w = v.split(/\\s+/).filter(Boolean);
    if (!w.length && !cat && !sig) { h.innerHTML = ''; cnt.textContent = ''; return; }
    const scored = [];
    for (const e of ix) {
      const c = cats[e[2]] || '', a = sigs[e[4]] || '';
      if (cat && c !== cat) continue;
      if (sig && a !== sig) continue;
      if (!w.length) { scored.push([0, e[0], e]); continue; }
      // Title hits outrank category hits; significance boosts.
      const t = e[1].toLowerCase(), cl = c.toLowerCase();
      let s = 0, ok = true;
      for (const x of w) {
        if (t.includes(x)) s += x.length > 4 ? 3 : 2;
        else if (cl.includes(x)) s += 1;
        else { ok = false; break; }
      }
      if (!ok) continue;
      if (a === 'major') s += 2; else if (a === 'notable') s += 1;
      scored.push([s, e[0], e]);
    }
    scored.sort((x, y) => y[0] - x[0] || (y[1] < x[1] ? -1 : 1));
    const hits = scored.slice(0, 200).map(r => r[2]);

    cnt.textContent = hits.length ? ('MATCHES: ' + hits.length + (hits.length === 200 ? '+ (capped at 200)' : '')) : 'MATCHES: 0';
    h.innerHTML = hits.map(e => {
      const u = '/day/' + e[0] + '/#' + e[3];
      const a = sigs[e[4]] || '', c = cats[e[2]] || '';
      const sigTag = a === 'major' ? '<span class="badge maj">[MAJOR]</span>' : (a === 'notable' ? '<span class="badge not">[NOTABLE]</span>' : '');
      return '<article class="entry ' + a + '"><div class="entry-meta-top">' +
        '<span class="commit-ref">commit ' + esc(e[3]) + '</span>' +
        '<span class="entry-utc">' + esc(e[0]) + '</span>' +
        '<div class="badges"><span class="badge cat">[' + esc(c) + ']</span>' + sigTag + '</div>' +
        '</div>' +
        '<h3><a href="' + u + '">' + esc(e[1]) + '</a></h3>' +
        '</article>';
    }).join('') || '<p style="color:var(--txt-subtle);margin:20px 0">$ No matches found for pattern.</p>';
  };

  q.addEventListener('input', () => {
    chips.forEach(c => c.classList.remove('active'));
    clearTimeout(t);
    t = setTimeout(go, 90);
  });
  if (fcat) fcat.addEventListener('change', go);
  if (fsig) fsig.addEventListener('change', go);

  chips.forEach(chip => {
    chip.addEventListener('click', () => {
      chips.forEach(c => c.classList.remove('active'));
      chip.classList.add('active');
      q.value = chip.dataset.filter || '';
      go();
    });
  });

  const params = new URLSearchParams(window.location.search);
  const initialQ = params.get('q') || (window.location.hash.startsWith('#q=') ? decodeURIComponent(window.location.hash.slice(3)) : '');
  const initialCat = params.get('cat') || '', initialSig = params.get('sig') || '';
  if (fcat && initialCat && [...fcat.options].some(o => o.value === initialCat)) fcat.value = initialCat;
  if (fsig && initialSig && [...fsig.options].some(o => o.value === initialSig)) fsig.value = initialSig;
  if (initialQ) {
    q.value = initialQ;
    chips.forEach(c => {
      if (c.dataset.filter && initialQ.toLowerCase().includes(c.dataset.filter.toLowerCase())) c.classList.add('active');
      else if (!c.dataset.filter && !initialQ) c.classList.add('active');
      else c.classList.remove('active');
    });
  }
  if (initialQ || initialCat || initialSig) {
    chips.forEach(c => c.classList.remove('active'));
    go();
  }
});
</script>`
  }))

  // ----- watchlist (saved searches + per-model RSS, client-side builder)
  const watchModels = [...new Set([...modelLive, ...modelRetired])].sort().map(m => `<option value="/models/${modelSlug(m)}/feed.xml">${esc(m)}</option>`).join('')
  await write(dist, 'watch/index.html', layout({
    title: 'Watch', path: '/watch/',
    desc: 'Build a personal Freebuff watchlist: per-model RSS feeds and saved search links.',
    body: `<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">WATCHLIST :: follow what matters</span><span>${modelLive.length} live models</span></div>`
      + `<p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">Pick a model for its dedicated RSS feed, or build a saved search link. No account, no tracking — just URLs for your reader.</p></div></section>`
      + `<div class="section-hdr"><h2>== PER-MODEL RSS ==</h2></div>`
      + `<div class="watch-row"><select id="wmodel">${watchModels}</select><a id="wmodellink" href="#">[open feed]</a><button id="wmodelcopy">[copy url]</button></div>`
      + `<div class="section-hdr"><h2>== SAVED SEARCH ==</h2></div>`
      + `<div class="watch-row"><input id="wq" type="search" placeholder="pattern (e.g. byok, model swap)..." size="28"><select id="wcat"><option value="">--any category</option>${SEARCH_CATS.map(c => `<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select><select id="wsig"><option value="">--any impact</option>${SEARCH_SIGS.map(s => `<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select></div>`
      + `<div class="watch-row"><a id="wlink" href="/search/">[open search]</a><button id="wcopy">[copy url]</button></div>`
      + `<p class="watch-hint">Tip: paste the feed URL or search link into any RSS reader — new matches surface on every hourly sync.</p>`
      + `<script>
const wm=document.getElementById('wmodel'),wml=document.getElementById('wmodellink'),wmc=document.getElementById('wmodelcopy');
const syncModel=()=>{const u=new URL(wm.value,location.origin).href;wml.href=wm.value;wmc.onclick=()=>navigator.clipboard.writeText(u).then(()=>{wmc.textContent='[copied!]';setTimeout(()=>wmc.textContent='[copy url]',1500)})};
wm.addEventListener('change',syncModel);syncModel();
const wq=document.getElementById('wq'),wc=document.getElementById('wcat'),ws=document.getElementById('wsig'),wl=document.getElementById('wlink'),wcp=document.getElementById('wcopy');
const syncSearch=()=>{const p=new URLSearchParams();if(wq.value.trim())p.set('q',wq.value.trim());if(wc.value)p.set('cat',wc.value);if(ws.value)p.set('sig',ws.value);const s=p.toString();const href='/search/'+(s?'?'+s:'');wl.href=href;const abs=new URL(href,location.origin).href;wcp.onclick=()=>navigator.clipboard.writeText(abs).then(()=>{wcp.textContent='[copied!]';setTimeout(()=>wcp.textContent='[copy url]',1500)})};
[wq,wc,ws].forEach(el=>el.addEventListener('input',syncSearch));syncSearch();
</script>`
  }))



  // ----- about (user-facing overview)
  await write(dist, 'about/index.html', layout({
    title: 'About', path: '/about/',
    body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">ABOUT :: Freebuff Changelog</span>
      <span>${entries.length.toLocaleString()} tracked changes</span>
    </div>
    <div class="man-body">
      <h4>WHAT IS THIS?</h4>
      <p>A commit-by-commit changelog for <a href="https://github.com/CodebuffAI/freebuff" target="_blank" rel="noopener">CodebuffAI/freebuff</a>, reconstructed from public git diffs. Upstream ships via automated snapshot merges with blank <em>"Sync public snapshot"</em> messages, so this project diffs each snapshot against its parent and extracts what actually changed: model swaps, version bumps, new slash commands, file-level churn. ${entries.length.toLocaleString()} entries from ${scannedCount.toLocaleString()} scanned commits, refreshed hourly.</p>

      <h4>HOW IT WORKS</h4>
      <p><strong>Deterministic first.</strong> Every sync commit is diffed parent-to-head. Model tables in both READMEs are parsed before and after and set-differenced (description-only edits cancel out); the slash-command registry (<code>cli/src/data/slash-commands.ts</code>) gets the same snapshot treatment; version bumps are read from release <code>package.json</code> files. Zero dependencies, stdlib only.</p>
      <p><strong>LLM summaries, cached forever.</strong> An optional model rewrites each entry once (keyed by commit SHA plus prompt version) into a technical 2-4 sentence summary. It sees only the diff plus extracted facts — model access/traits, command names, files, stats — and is schema-validated with one repair retry. No provider configured means deterministic summaries only; nothing breaks.</p>
      <p><strong>Every claim links to proof.</strong> Each entry carries its commit SHA, compare URL, inline diff (lazy-loaded, lockfiles and test-only hunks stripped), and per-file stats. Model swaps render before/after README rows inline.</p>

      <h4>WHAT WE TRACK</h4>
      <p><strong>Model Catalog</strong> (${(cats.get('Model Catalog') || 0)} changes): additions, retirements, and swaps in the free picker, with access level and trait columns — plus a <a href="/models/">catalog timeline</a> and per-model pages with watch feeds.<br>
      <strong>Releases</strong> (${vers.length} tracked): CLI and core <code>package.json</code> bumps with per-release pages listing every commit in range.<br>
      <strong>Commands</strong> (${(cats.get('Commands') || 0)} changes): new or removed <code>/slash-commands</code> from the registry (renames surface as add+remove).<br>
      <strong>CLI</strong> (${(cats.get('CLI') || 0).toLocaleString()}), <strong>Core</strong> (${(cats.get('Core') || 0).toLocaleString()}), <strong>SDK</strong> (${(cats.get('SDK') || 0)}), <strong>Agent Runtime</strong> (${(cats.get('Agent Runtime') || 0)}), <strong>Agents</strong> (${(cats.get('Agents') || 0)}), <strong>LLM Providers</strong> (${(cats.get('LLM Providers') || 0)}), <strong>Packaging</strong> (${(cats.get('Packaging') || 0)}), <strong>Docs</strong> (${(cats.get('Docs') || 0)}), <strong>Internal</strong> (${(cats.get('Internal') || 0).toLocaleString()}): file-path categorization with per-file add/remove/rename tracking.<br>
      <strong>Significance:</strong> <code>major</code> (model/version/security/breaking), <code>notable</code> (visible behavior, new files, large churn), <code>minor</code> (internal). Deterministic by default; the LLM may only override with diff evidence.<br>
      <strong>In-Flight PRs:</strong> open upstream pull requests with diffstat and 120-line diff previews, pruned when merged.</p>

      <h4>LIMITS</h4>
      <p>Snapshots squash upstream history, so intra-snapshot sequencing is approximate and authorship resolves to the snapshot bot. Diffs older than 90 days are pruned (day pages fall back to GitHub compare links). AI summaries describe only what the diff shows — no research, no speculation on model capabilities beyond the README row.</p>

      <h4>FOLLOW ALONG</h4>
      <p><a href="/feed.xml">RSS</a> (major + notable), <a href="/feed-models.xml">models only</a>, <a href="/feed-releases.xml">releases only</a>, per-model feeds on each <a href="/models/">model page</a>. <a href="/search/">Search</a> supports category and impact filters; <a href="/stats/">stats</a> charts churn and cadence; <a href="/watch/">watchlist</a> builds saved-search links. <a href="/archive/">Archive</a> holds every day and release. Source: hourly GitHub Action plus a local backfill daemon, both pushing <code>data/</code>; Cloudflare deploys on push.</p>
    </div>
  </div>
</section>`
  }))

  // ----- open PRs page (community activity ahead of merges, with diff previews)
  if (openPrs?.length) {
    const cards = openPrs.map(p => {
      const stats = (p.additions != null && p.deletions != null)
        ? `<span class="diffstat"><b>+${p.additions}</b> / <i>−${p.deletions}</i></span>${p.files != null ? `<span style="font-size:.72rem;color:var(--txt-subtle)">${p.files} file${p.files === 1 ? '' : 's'}</span>` : ''}`
        : ''
      const preview = p.hasDiff
        ? `<details class="diff-viewer" data-pr="${p.number}">
<summary class="diff-toggle">
  <span class="diff-toggle-left">
    <span class="diff-arrow">&gt;</span>
    <span>View diff preview</span>
  </span>
  ${stats}
</summary>
<div class="diff-body"><span class="diff-loading">Loading diff…</span></div>
</details>`
        : ''
      return `<article class="pr-card">
  <div class="pr-card-header">
    <span class="pr-status ${p.draft ? 'draft' : 'open'}">[${p.draft ? 'DRAFT' : 'OPEN PR'}]</span>
    <a href="${esc(p.url)}" target="_blank" rel="noopener">#${p.number}</a>
  </div>
  <h3 class="pr-title"><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.title)}</a></h3>
  <div class="pr-meta">
    <span>#${p.number} by ${esc(p.author || 'contributor')}</span>
    <span>&middot;</span>
    <span>${esc((p.updated || p.created || '').slice(0, 10))}</span>
    ${stats ? `<span>&middot;</span>${stats}` : ''}
    ${p.draft ? '<span>&middot;</span><span style="color:var(--txt-subtle)">draft</span>' : ''}
  </div>
  ${preview}
</article>`
    }).join('')

    await write(dist, 'in-flight/index.html', layout({
      title: 'In flight', path: '/in-flight/',
      body: `<section class="hero">
  <div class="term-box">
    <div class="term-box-hdr">
      <span class="term-box-title">PULL_REQUESTS :: CodebuffAI/freebuff [in flight]</span>
      <span>${openPrs.length} open</span>
    </div>
    <p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">
      Community contributions awaiting merge or snapshot sync. Updated ${esc(fmtDateHuman(generated))} UTC.
    </p>
  </div>
</section>
<div class="pr-list">${cards}</div>`
    }))
  }

  // ----- feeds: main (major+notable), models-only, releases-only
  const titleOf = (e) => e.ai?.title || e.title || deriveTitleSafe(e)
  const mainItems = entries.filter(e => e.significance !== 'minor').slice(0, 60).map(e => feedItem(SITE.url, e, titleOf)).join('')
  const modelItems = modelEntries.slice(0, 60).map(e => feedItem(SITE.url, e, titleOf)).join('')
  const releaseItems = [...vers].reverse().slice(0, 60).map(e => feedItem(SITE.url, e, titleOf)).join('')
  await write(dist, 'feed.xml', feedXml(SITE.url, SITE.name, SITE.desc, generated, 'feed.xml', `${SITE.name} (unofficial)`, SITE.desc, mainItems))
  await write(dist, 'feed-models.xml', feedXml(SITE.url, SITE.name, SITE.desc, generated, 'feed-models.xml', `${SITE.name}: models (unofficial)`, 'Model catalog additions, retirements, and swaps in the Freebuff free picker.', modelItems))
  await write(dist, 'feed-releases.xml', feedXml(SITE.url, SITE.name, SITE.desc, generated, 'feed-releases.xml', `${SITE.name}: releases (unofficial)`, 'Freebuff CLI and core package version bumps.', releaseItems))
  const mainJsonItems = entries.filter(e => e.significance !== 'minor').slice(0, 60).map(e => jsonItem(SITE.url, e, titleOf))
  await write(dist, 'feed.json', feedJson(SITE.url, generated, `${SITE.name} (unofficial)`, SITE.desc, 'feed.json', mainJsonItems))
  await write(dist, 'feed.xsl', FEED_XSL)
  await writeBinary(`${dist.replace(/\/$/, '')}/favicon.ico`, generateFaviconIco())
  await write(dist, 'favicon.svg', FAVICON_SVG)
  await writeBinary(`${dist.replace(/\/$/, '')}/icon-192.png`, generateIconPng(192))
  await writeBinary(`${dist.replace(/\/$/, '')}/icon-512.png`, generateIconPng(512))
  await write(dist, 'manifest.webmanifest', JSON.stringify({
    name: SITE.name,
    short_name: 'FreebuffLog',
    description: SITE.desc,
    start_url: '/',
    display: 'standalone',
    background_color: '#0d1117',
    theme_color: '#0d1117',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' }
    ]
  }))

  await write(dist, 'api/entries.json', JSON.stringify({ generatedAt: generated, head: changelog.headSha, total: entries.length, latest: entries.slice(0, 60) }))
  await write(dist, 'api/status.json', JSON.stringify({
    generatedAt: generated,
    headSha: changelog.headSha,
    total: entries.length,
    days: byDay.length,
    releases: vers.length,
    models: { changes: modelEntries.length, live: modelLive.length },
    openPrs: openPrs?.length || 0
  }))

  // ----- sitemap index (day pages change daily, release/pages rarely)
  const urlset = (urls) => `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u => `<url><loc>${SITE.url}${u}</loc></url>`).join('')}</urlset>`
  const dayUrls = byDay.map(d => `/day/${d.day}/`)
  const relUrls = vers.map(v => `/release/${v.version}/`)
  const modelUrls = ['/models/', ...[...byModel.keys()].map(m => `/models/${modelSlug(m)}/`)]
  const pageUrls = ['/', '/archive/', '/search/', '/about/', '/models/', '/stats/', '/watch/', ...(openPrs?.length ? ['/in-flight/'] : [])]
  await write(dist, 'sitemap-days.xml', urlset(dayUrls))
  await write(dist, 'sitemap-releases.xml', urlset(relUrls))
  await write(dist, 'sitemap-models.xml', urlset(modelUrls))
  await write(dist, 'sitemap-pages.xml', urlset(pageUrls))
  await write(dist, 'sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['sitemap-days.xml', 'sitemap-releases.xml', 'sitemap-models.xml', 'sitemap-pages.xml'].map(f => `<sitemap><loc>${SITE.url}/${f}</loc></sitemap>`).join('')}</sitemapindex>`)
  await write(dist, 'robots.txt', `User-agent: *\nAllow: /\nSitemap: ${SITE.url}/sitemap.xml\n`)
  await write(dist, '_headers', `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
/favicon.ico
  Content-Type: image/x-icon
  Cache-Control: public, max-age=604800
/favicon.svg
  Content-Type: image/svg+xml
  Cache-Control: public, max-age=604800
/icon-192.png
  Content-Type: image/png
  Cache-Control: public, max-age=604800
/icon-512.png
  Content-Type: image/png
  Cache-Control: public, max-age=604800
/manifest.webmanifest
  Content-Type: application/manifest+json
  Cache-Control: public, max-age=86400
/feed.json
  Content-Type: application/feed+json; charset=utf-8
  Cache-Control: public, max-age=600
/og/*
  Content-Type: image/svg+xml
  Cache-Control: public, max-age=86400
/feed.xsl
  Content-Type: text/xsl; charset=utf-8
  Cache-Control: public, max-age=86400
/api/*
  Access-Control-Allow-Origin: *
  Cache-Control: public, max-age=300
/*.json
  Access-Control-Allow-Origin: *
/
  Cache-Control: public, max-age=300
/index.html
  Cache-Control: public, max-age=300
/search-index.json
  Cache-Control: public, max-age=3600
/feed.xml
  Cache-Control: public, max-age=600
/feed.json
  Cache-Control: public, max-age=600
/feed-models.xml
  Cache-Control: public, max-age=600
/feed-releases.xml
  Cache-Control: public, max-age=600
/sitemap.xml
  Cache-Control: public, max-age=86400
/sitemap-days.xml
  Cache-Control: public, max-age=86400
/sitemap-releases.xml
  Cache-Control: public, max-age=86400
/sitemap-models.xml
  Cache-Control: public, max-age=86400
/sitemap-pages.xml
  Cache-Control: public, max-age=86400
/day/*
  Cache-Control: public, max-age=86400
/release/*
  Cache-Control: public, max-age=86400
/diffs/*
  Content-Type: text/plain; charset=utf-8
  Cache-Control: public, max-age=31536000, immutable
  Access-Control-Allow-Origin: *
/pr-diffs/*
  Content-Type: text/plain; charset=utf-8
  Cache-Control: public, max-age=3600
  Access-Control-Allow-Origin: *
/models/
  Cache-Control: public, max-age=3600
`)
  await write(dist, '404.html', layout({ title: 'Not found', path: '/404', noindex: true, body: '<section class="hero"><div class="term-box"><div class="term-box-hdr"><span class="term-box-title">ERROR :: 404 NOT FOUND</span></div><p style="margin:6px 0 0;font-size:.84rem;color:var(--txt-dim)">No commit or snapshot shipped at this path. <a href="/">&larr; [back to index]</a></p></div></section>' }))
  return { entries: entries.length, days: byDay.length, releases: vers.length }
}
